Invoke update_storage_group_status() for LRC groups
yandex/mastermind pull request #254
Opened 2016-09-26 14:53 UTC by v-nikulichev

2016-09-26 20:44 UTC, nobodyisme requested changes

2016-09-26 20:44 UTC, nobodyisme commented on src/cocaine-app/storage.py
>              status = self.update_storage_group_status()
В этом месте будет зваться проверка `Groupset.check_groups`, которая, кажется, работает на самом деле только для `Replicas`, а для других групсетов нет. Надо переопределить этот метод в классе `Lrc822v1Groupset`, чтобы он должным образом работал.

2016-09-27 16:34 UTC, v-nikulichev commented on src/cocaine-app/storage.py
>              status = self.update_storage_group_status()
Готово

2017-03-27 15:54 UTC, nobodyisme commented
Implemented in https://github.com/yandex/mastermind/pull/472

2017-03-27 15:54 UTC, closed without merging