Imporve `couple break`: update group histories
yandex/mastermind pull request #307
Opened 2016-11-11 12:09 UTC by jkorvin

Resolves: #MDS-1233

2016-11-18 13:53 UTC, nobodyisme commented
Ты забыл про следующий usecase:
- мастермайнд работает как несколько независмых процессов на разных хостах;
- couple break совершается на одном из этих процессов, внутри этого воркера происходит изменение состояния -- он отвязывает группу от капла, пишет запись в историю;
- другие воркеры эту запись в истории видят. Но сейчас ничего предпринимать не будут, они никак эти записи не анализируют. Поэтому они будут помнить про то, что группы всё еще в капле. Нужно научить применять записи о couple break из истории.

2016-11-18 13:53 UTC, nobodyisme requested changes

2016-11-18 13:53 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            if len(group_history.couples) == 0 or group_history.couples[-1].couple != couple_as_tuple:
На самом деле эти проверки лишние. Если в истории группы нет каплов, то новую запись о том, что группа нигде не живет, сделать не помешает. Сверять старую запись с текущими группами тоже незачем, мы по факту говорим, что группа нигде не живет, раз капла больше нет, старая история тут не должна играть роли.

2016-11-18 13:57 UTC, nobodyisme requested changes

2016-11-18 13:57 UTC, nobodyisme commented on src/cocaine-app/balancer.py
> +                logger.error('Failed to remove couple {0} from groups {1} history: {2}'.format(
тут лучше использовать `logger.exception`, который сам залогирует исключение с трейсбеком - тогда из самой строки можно его убрать (`: {2}`)

2016-11-18 13:57 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +    def couple_break(self, couple_as_tuple, record_type=None):
В питоне не принято упоминать типы переменных в их названии. И то, что метод называется `as_tuple()`, историческая ошибка :-). Назови этот параметр просто] `group_ids`, этого будет вполне достаточно

2016-11-24 22:37 UTC, nobodyisme requested changes

2016-11-24 22:37 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                    previous_couple == couple_record.couple_str
Очень сложное условие, которое заодно ещё и выполняет две цели одновременно -- фильтрацию записей и поиск предыдущего капла. Нужно разбить, чтобы читалось легче.

2016-11-24 22:37 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                        storage.couples[previous_couple].destroy()
Поскольку мы обрабатываем историю **группы**, странно, что мы берём какой-то капл из истории и уничтожаем его. Более ожидаемым в этом месте было бы сравнение текущего капла группы с `previous_couple`, и его разрушение.
Помимо логики -- стилистически не очень здорово, что в основной ветке `if-а` ничего не происходит, а вся работа ведется в `else`.

2016-11-24 22:37 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                    previous_couple == couple_record.couple_str
Я бы определение предыдущего капла сделал бы сильно проще -- на каждой итерации цикла смотрел бы, если ли у текущей записи капл, и если есть, сохранял бы его в `previous_couple`.

2016-11-24 22:37 UTC, nobodyisme commented on src/cocaine-app/history.py
> +    def couple_str(self):
Это лишний метод, который повторяет логику объекта `Couple`, и ответственность за формирование `id` объекта несёт именно `Couple`, поэтому дублировать её здесь неправильно. Лучше в месте сравнения брать `record.couple` и сравнивать с `group.couple.as_tuple()`.

2016-11-25 13:51 UTC, nobodyisme requested changes

2016-11-25 13:51 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            previous_couple = group.couple.as_tuple()
В этот момент ты не можешь быть уверен, что `group.couple != None`, поэтому вызов `as_tuple()` может привести к исключению.

2016-11-25 13:51 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                    previous_couple = couple_record.couple
Почему ты не хочешь в начало цикла вынести что-то вроде:
```
if couple_record.couple:
    previous_couple = couple_record.couple
```

У тебя всё еще логика фильтрации записей путается с логикой обработки записей.

2016-11-25 13:51 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                if previous_couple and couple_record.couple == ():
Тут проверка `previous_couple`, кажется, мешает. Обработку нужно производить всегда, когда `couple_record.couple` пустой:
1) group.couple не None и `previous_couple` совпадает с group.couple - удалить капл
2) group.couple не None и `previous_couple` не совпадает с group.couple - поругаться
3) group.couple None - ничего не делать.

2016-11-25 13:51 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                if previous_couple and couple_record.couple == ():
В условии `couple_record.couple == ()` часть `== ()` лишняя.

2016-11-25 13:51 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                    if previous_couple == str(group.couple):
Это не будет работать, у тебя же в `previous_couple` лежит тапл.

2016-11-25 13:51 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                    elif group.couple != ():
`elif group.couple != ():` -> `elif group.couple:`

2016-11-25 16:48 UTC, jkorvin commented on src/cocaine-app/infrastructure.py
> +                    previous_couple = couple_record.couple
не понял:
1) Идеологически я бы сказал, что фильтрация - это простейшая обработка "done nothing!".

2) а если в начало цикла вынести previous_couple = couple_record.couple, тогда это переменная вообще не нужна и предыдущий капл уже никак не получить.

2016-11-25 20:05 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                    previous_couple = couple_record.couple
Не совсем. Фильтрация - это отсев записей, которые обрабатывать не нужно.

Нам предыдущий капл нужно знать только в том случае, когда текущая запись говорит о том, что она про `couple break`, а это значит, что в *текущей записи* нет `couple`, и `if couple_record.couple` в начале итерации вернёт `False`. Таким образом до конца итерации мы в `previous_couple` имеем `couple` из предыдущей записи, где он был не нулевым.

2016-11-25 20:06 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +                if couple_record.couple == () and group.couple:
`couple_record.couple == ()` -> `not couple_record.couple`

2016-11-25 21:47 UTC, jkorvin commented on src/cocaine-app/infrastructure.py
> +                    previous_couple = couple_record.couple
Окей; то, что так будет работать - согласен.
Но переменная previous_couple не будет отражать своей сути.
И кажется ты говорил, что этот loop хотел устроить так, чтобы в будущем можно было пользоваться особо не разбираясь и помнить меньше деталей. Когда у нас переменная всегда является предыдущим элементом это понятно, но когда она то предыдущий, то текущий - может быть, это увеличивает сложность?

2016-11-25 21:54 UTC, jkorvin commented on src/cocaine-app/infrastructure.py
> +                if couple_record.couple == () and group.couple:
а если я хотел специально показать, что couple_record.couple это какой-то tuple и мы ожидаем его пустой, т.к. если написать `not couple_record.couple`, то можно подумать "а может ли быть там None?". И, либо проверять может ли он быть None, либо думать а правильно ли мы будем работать если даже там будет None.

Или так все-равно делать не стоит?

2016-11-29 14:37 UTC, merged