Refactor code
yandex/mastermind pull request #310
Opened 2016-11-16 11:12 UTC by jkorvin

2016-11-16 11:13 UTC, jkorvin commented on src/cocaine-app/infrastructure.py
> -        except (ValueError, TypeError, KeyError):
Исправление: раньше в ошибке node_backend_str - мог быть не определен.
+ насколько понял TypeError вообще не может вызваться

2016-11-16 11:14 UTC, jkorvin commented on src/cocaine-app/jobs/job.py
> +    def _involved_groups(self):
эти property используются в этом классе без определения

2016-11-16 11:15 UTC, jkorvin commented on src/cocaine-app/jobs/tasks/__init__.py
> -from task import Task
видимо, раньше Task использовался.

2016-11-18 11:44 UTC, nobodyisme requested changes

2016-11-18 11:44 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            map(int, (port, family, backend_id))
Это слишком неявный способ проверки типов, не стоит так делать, лучше всего проверять всё явно и в исключении подробно описать, что произошло.
Конкретно в этом случае можно вообще забить на эти проверки, они и раньше были лишними. Достаточно искать node_backend_str в storage.node_backends -- если такого нет, то будет понятный KeyError.

2016-11-18 11:44 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            raise ValueError('defrag_node_backend_cmd need `request` with len(request) >= 4')
Это плохое сообщение об ошибке, потому что это то, что увидит клиент. Ему это ничего не скажет. Здесь, к сожалению, старый формат передачи параметров, поэтому совсем красиво сделать нельзя, но как-нибудь так:
Request should contain parameters in the following order: host, port, family, backend_id

2016-11-18 11:44 UTC, nobodyisme commented on src/cocaine-app/jobs/job.py
> -            pass
`pass` не нужно удалять. Я использую его для того, чтобы явным образом дать понять, что это исключение пропускается. Иначе каждый раз я пытаюсь понять, не забыл ли я сделать `raise`.

2016-11-18 11:44 UTC, nobodyisme commented on src/cocaine-app/jobs/job.py
> +        raise NotImplementedError('_involved_groups property-method for {} should be '
Оставь, пожалуйста, просто `property`, слово `method` уже лишнее.

2016-11-18 11:44 UTC, nobodyisme commented on src/cocaine-app/jobs/tasks/__init__.py
> -from task import Task
Он здесь для того, чтобы можно было использовать import вида:
from tasks import Task, поэтому убирать не стоит.

2016-11-18 11:44 UTC, nobodyisme commented on src/cocaine-app/jobs/job_factory.py
> +        job_types = {
Теперь `job_types` можно вынести в константу в сам модуль:
```
JOB_TYPES = {
    JobTypes.TYPE_MOVE_JOB: MoveJob,
    ...
}
```  

Насчет форматирования -- не видел такого стиля, где значение переносится на следующую строку и отбивается табом. Давай так не будем делать, тут и в одну строку всё ок.

2016-11-18 11:44 UTC, nobodyisme commented on src/cocaine-app/jobs/tasks/__init__.py
> +        Tasks = {
Переменные в питоне не принято именовать с заглавной буквы. Знаю только одно исключение - когда ты присваиваешь ей какой-то тип. В данном случае вообще стоит сделать по аналогии с JOB_TYPES, который я описал выше.

2016-11-18 11:44 UTC, nobodyisme commented on src/mastermind
> -d = Dispatcher(globaloptions=(app_param,))
А почему ты его здесь убираешь? По хорошему он здесь не мешает, но если вдруг мы захотим сделать прямую команду на уровне этого диспатчера (без использования дочернего), то app нам как раз понадобится.

2016-11-24 21:29 UTC, nobodyisme requested changes

2016-11-24 21:29 UTC, nobodyisme commented on src/cocaine-app/jobs/tasks/__init__.py
> +    TASKS = {
Неплохо было бы назвать единообразно с `JOB_TYPES` -- `TASK_TYPES`

2016-11-24 21:29 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +        try:
Давай уберём отсюда `try..except`, объект storage.node_backends уже умеет кидать правильное исключение с правильным сообщением об ошибке, если ей передан бэкенд, который не существует.

2016-11-25 12:29 UTC, merged