[Draft] ttl cleanup scheduler
yandex/mastermind pull request #311
Opened 2016-11-16 16:43 UTC by annamel

Just putting Igor logic into mastermind

2016-11-20 19:22 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +            WHERE  sum_expired_size >= {trigger};
Чтобы не делать селект на селекте, существует специальный параметр `HAVING`.

2016-11-20 19:28 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    couple = int(unicode(row[0]))
Зачем тут нужно приводить `couple_id` к `unicode`?

2016-11-28 21:41 UTC, nobodyisme requested changes

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        aggregate_query = """
Шаблон запроса нужно вынести в переменную класса или глобальную.

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        preaggregate_query = """
Шаблон запроса нужно вынести в переменную класса или глобальную.

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        for table in r.results:  # access to results blocks until they are ready
Что такое `r.results` и почему он может возвращать несколько таблиц? Действительно ли нужно обрабатывать все таблицы?

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    logger.debug("couple %d is valid", couple)
Это бессмысленное логирование, его нужно убрать.

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        main_table_per_day = "statbox/mds-proxy-log/{}".format(date_iso)
Этот шаблон не должен быть захардкожен, его тоже неплохо бы вынести в конфиг.

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    return None
Здесь нельзя возвращать `None`, потому что при использовании этой функции ты рассчитываешь, что вернётся какой-то осмысленный результат. Вполне нормально будет тут кидать исключение.

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                return None
Я бы вообще не стал тут делать перехватывание исключения, но в любом случае `None` возвращать нельзя, как и выше.

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
Это не таймаут на запрос, а проверка постфактум. Очень странно, раз уж мы позволили ждать сколько угодно, отбрасывать результат успешного запроса.

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    logger.exception("YQL request excepted %s", query)
Не нужно логировать запрос, в нашем случае он слишком объемный.

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    return result
Что в этом случае будет содержать `result`? Почему его можно успешно возвращать?

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        return result
Что в этом случае содержит `result`?

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            if self.params.get('ttl_cleanup', {}).get('enabled', False):
Добавь, пожалуйста, секцию `ttl_cleanup` в пример конфигурации в `examples/mastermind.conf`.

2016-11-28 21:41 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            seconds=self.params.get('ttl_cleanup', {}).get('ttl_cleanup_periodic', 60 * 15))
`ttl_cleanup_periodic` - в других планировщиках название похожего параметра имеет другой шаблон, например, `couple_defrag_period`. Переименую, пожалуйста.

2016-11-28 22:23 UTC, nobodyisme commented
Ещё нужно избавиться от форматирования с помощью синтаксиса вида `%s`, `%d` и так далее, в мастермайнде код-стайл сейчас предполагает варианты `{}` и `{some_var_name}`.

2016-11-29 06:24 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    return result
Он будет содержать  None. Но я помню твою ремарку про None

2016-11-29 06:29 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    logger.debug("couple %d is valid", couple)
это отладочная история. И она поэтому идет с уровнем не info, а debug. Зато потом она позволяет посмотреть какие каплы нуждались в чистке с точке зрения YT vs на какие каплы в какой последовательности были натравлены миньоны.

2016-11-29 06:29 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        main_table_per_day = "statbox/mds-proxy-log/{}".format(date_iso)
Я его вынесла уже. Похоже ревью не обновила. Спасибо большое, что заметил

2016-11-29 08:03 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
Ребята из YQL обещали добавить ручку на timeout (https://st.yandex-team.ru/YQL-1527). А нам этот ассерт нужен чтобы понимать когда переходить на другую схему работы без мучения YTя. Это к вопросу о не-фатальных наблюдаемых "алертах", которые мы обсуждали и решили оставить "на потом".

2016-11-29 12:50 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        for table in r.results:  # access to results blocks until they are ready
Буду разбираться в разделе про оптимизацию YQL request-а. У них в примерах именно несколько таблиц. А текущий запрос работает.

2016-11-29 13:03 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +            WHERE  sum_expired_size >= {trigger};
Когда буду переделывать YQL запросы и тестировать их по времени, учту и переделаю. Спасибо!

2016-11-29 14:15 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        preaggregate_query = """
Fixed in https://github.com/yandex/mastermind/pull/311/commits/808a99a19c77cd1a34d2ad6416390a670b6394eb

2016-11-29 14:15 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            seconds=self.params.get('ttl_cleanup', {}).get('ttl_cleanup_periodic', 60 * 15))
Fixed in https://github.com/yandex/mastermind/pull/311/commits/df804b5194ac65d6a365dda7cf7253cd1fc2f821

2016-11-29 14:16 UTC, annamel commented
Форматирование починено в https://github.com/yandex/mastermind/pull/311/commits/808a99a19c77cd1a34d2ad6416390a670b6394eb

2016-11-29 14:20 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        main_table_per_day = "statbox/mds-proxy-log/{}".format(date_iso)
Fixed in https://github.com/yandex/mastermind/pull/311/commits/f7c40b6c6935d1d3f60b4dd59f2e3df4c76114eb

2016-11-29 14:20 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        aggregate_query = """
Fixed in https://github.com/yandex/mastermind/pull/311/commits/808a99a19c77cd1a34d2ad6416390a670b6394eb

2016-11-29 14:21 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        return result
Fixed in https://github.com/yandex/mastermind/pull/311/commits/808a99a19c77cd1a34d2ad6416390a670b6394eb

2016-11-29 14:21 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    return result
Fixed in https://github.com/yandex/mastermind/pull/311/commits/808a99a19c77cd1a34d2ad6416390a670b6394eb

2016-11-29 14:21 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    logger.exception("YQL request excepted %s", query)
Fixed in https://github.com/yandex/mastermind/pull/311/commits/808a99a19c77cd1a34d2ad6416390a670b6394eb

2016-11-29 14:21 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                return None
Fixed in https://github.com/yandex/mastermind/pull/311/commits/808a99a19c77cd1a34d2ad6416390a670b6394eb

2016-11-29 14:37 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            if self.params.get('ttl_cleanup', {}).get('enabled', False):
Fixed in https://github.com/yandex/mastermind/pull/311/commits/3e401778f178741610800a49b28e8245e296de80

2016-11-29 15:12 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    logger.exception("couple {!s} is invalid".format(couple))
Не стоит использовать форматирование с такими опциями, объект сам должен отвечать за своё представление в строке (через имплементацию __str__ метода). В особых случаях, когда без этого не обойтись, используй, пожалуйста, явное приведение аргумента через `"some object: {}".format(str(some_object))`. Учитывая, что у тебя тут `int`, совершенно точно делать ничего не нужно, достаточно `"couple {} is invalid".format(couple)`.

2016-11-29 17:34 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    logger.exception("couple {!s} is invalid".format(couple))
Здесь точно не int. Мы же как раз за-except-ились на попытке привести к int-у. Что за объект мы вычитали, мы не знаем, поэтому казалось логичным использовать строковое представление. И мне бы помогло, чтобы ты аргументировал, чем "{!s}".format(o) хуже чем "{}".format(str(o)). Почему?

2016-12-09 14:33 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            # XXX: Prepare aggregate table from time to time, not always
Фичу из этого комментария обязательно нужно реализовать в этом пулл-реквесте, потому что нужна гарантия, что:
1) операция по агрегации запускается один раз в день;
2) операция по агрегации запускается только с одного воркера.

Иначе будет возможно несколько параллельных одинаковых вставок в агрегированную таблицу.

2016-12-09 14:34 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        couple_list = self._get_yt_stat()
`_get_yt_stat` может вернуть `None`, в этом случае при итерировании по `couple_list` мы получим исключение.

2016-12-09 14:35 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            logger.fatal('Found {} unfinished ttl cleanup jobs'.format(count))
Откуда у нас берётся ограничение на 1 джобу в момент времени? Почему в этом случае мы не останавливаемся?

2016-12-09 14:39 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            self.ttl_cleanup(request)
Метод `ttl_cleanup` - ручка внешнего API, которую нельзя использовать изнутри мастермайнда. Формирование объекта `request`, который имитирует поведение кокаиновского клиентского запроса, для того, чтобы позвать код изнутри, -- странная затея. Логику создания джоба нужно вынести в отдельный метод с нормальными явными параметрами.

2016-12-09 14:40 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            self.ttl_cleanup(request)
Важное замечание: ручка `ttl_cleanup` должна быть обёрнута декоратором `concurrent_handler`, как и остальные ручки, иначе её исполнение будет блокировать остальные клиентские запросы. Поправь это, пожалуйста, в рамках этого пулл-реквеста.

2016-12-09 14:47 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        self.aggregate_query = """
Шаблон запроса нужно вынести в атрибут класса:
```
class YqlWrapper(object):
    AGGREGATE_QUERY_TPL = """
        SELECT couple_id ...
    """

Отступы лучше сохранить, прижимать строки к левому краю не стоит, это мешает читать код.

Пример форматирования:
https://github.yandex-team.ru/InfraComponents/s3-mds-proxy/blob/master/s3mds/db/client.py#L65

2016-12-09 14:47 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        self.preaggregate_query = """
Аналогично комментарию выше про sql-запрос.

2016-12-09 14:52 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
Это не даёт мне понять, почему после долгого ожидания и всё-таки получения ответа мы забиваем на результат и кидаем исключение?

2016-12-09 14:57 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +    TTL_CLEANUP_LOCK = 'planner/couple_ttl_cleanup'
Почему `couple_ttl_cleanup`? Кажется, тут достаточно `planner/ttl_cleanup`.

2016-12-09 14:57 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
Чтобы не пропустить некорректное поведение. Когда будет реализован мониторинг на mm, то будем делать по-другому

2016-12-09 14:58 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            logger.fatal('Found {} unfinished ttl cleanup jobs'.format(count))
Это не ограничение. Просто логгинг, пока не реализовали полноценную историю.

2016-12-09 14:59 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
В чем заключается некорректное поведение, когда результат запроса успешен?

2016-12-09 15:03 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            logger.fatal('Found {} unfinished ttl cleanup jobs'.format(count))
Почему тогда логгинг уровня `fatal` (который на самом деле `error`)?

2016-12-09 15:13 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        logger.fatal("Create ttl_cleanup_job for couple {!s}".format(iter_group.couple))
Почему уровень `fatal`?
Убери, пожалуйста, `{!s}`.

2016-12-09 15:14 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            # Configure parameters for work with IT
`IT` -> `YT`

2016-12-09 15:15 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        :return: list of couples with expired records volume above specified
`list of couples` -> `list of couple ids`

2016-12-09 15:43 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            expired_threshold = self.params.get('ttl_cleanup', {}).get('ttl_threshold', 10737418240)
Интересно, а почему переменная в коде называется не так, как переменная в конфиге? 
В примере конфига отсутствует `ttl_threshold`.
Оставь, пожалуйста, комментарий, что означает `10737418240`.

2016-12-09 15:45 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        :return:
`return` в коде есть, а описания нет.

2016-12-09 15:46 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        Update aggregate table from YT. The processing may take up to ... time
`to ... time`?

2016-12-09 15:54 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        :param expired_threshold: a couples with expired volume above param are suspected
Почему `suspected`? Мы их вроде безусловно чистим, разве нет?

2016-12-09 15:57 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    couple = int(unicode(row[0]))
Done

2016-12-09 15:57 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    return None
Done

2016-12-09 16:04 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            expired_threshold = self.params.get('ttl_cleanup', {}).get('ttl_threshold', 10737418240)
Потому что от префикса ttl в глазах рябит. :) остальное поправлю, сейчас дозалью

2016-12-09 16:10 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        :param expired_threshold: a couples with expired volume above param are suspected
Мы запускаем лангольер, да. Но пока он не пройдет, мы не можем наверняка сказать правильные ли данные лежат в таблице или нет.

2016-12-09 16:17 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                logger.exception("YQL ping excepted {}{}".format(self._cluster, self._token))
Это исключение с полным стек-трейсом будет залогировано дважды, это правда необходимо? Можно убрать этот try..except блок.

2016-12-09 16:31 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                logger.exception("YQL ping excepted {}{}".format(self._cluster, self._token))
Потерялся пробел между кластером и токеном.

2016-12-09 16:36 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                logger.exception("YQL ping excepted {}{}".format(self._cluster, self._token))
Важно:

Везде, где логируется токен, нужно перейти на логирование `self._token[:20]` и писать, соответственно `token prefix`. Можно сделать специальный `property`, чтобы при каждом использовании это не повторять.

2016-12-09 16:37 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    logger.error("YQL failed #{}: {}[{}] ({},{!s})".format(attempt, result.status,
Нужно избавиться от `{!s}`.

2016-12-09 16:37 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                        logger.error("YQL query result error {!s}".format(error))
Нужно избавиться от `{!s}`.

2016-12-09 16:39 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        raise AssertionError("YQL request attempts has exhausted {} {}".format(self._attempts, query))
Это не `AssertionError`, лучше всего поменять на `RuntimeError`.

2016-12-09 16:39 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    raise
Почему мы в этом случае не делаем `retry`, хотя у нас есть количество попыток `attempts`?

2016-12-09 16:56 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    logger.error("YQL failed #{}: {}[{}] ({},{!s})".format(attempt, result.status,
Кстати, чем отличается вывод в случае `{!s}` и простого `{}`?

2016-12-09 17:05 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        :return list of couples with expired date more then trigger
А здесь про `date`, или про `data`? Потому что именно объем `data` имеет отношение к триггеру.
`then` -> `than`

2016-12-09 17:06 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        :param expired_threshold: a couples with expired volume above param are suspected
`a couples` -> `couples`

2016-12-09 17:07 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                logger.error("empty result")
Почему это считается ошибочной ситуацией?

2016-12-09 17:08 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        for table in r.results:  # access to results blocks until they are ready
Уже писал про это, но чтоб не забыть -- почему тут происходит итерация по результатам? Разве у нас может быть несколько результатов?

2016-12-09 17:08 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    logger.exception("couple {!s} is invalid".format(row[0]))
Нужно избавиться от `!s`

2016-12-09 17:13 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            logger.fatal('Found {} unfinished ttl cleanup jobs'.format(count))
Точнее, вопрос в следующем -- почему в логе на каждый запуск планировщика я буду видеть сообщение об ошибке?

2016-12-09 17:15 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        :param date: data from which day to use for update
`data` -> `date`

2016-12-09 20:21 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +        :param expired_threshold: a couples with expired volume above param are suspected
Но мы же будем в любом случае итерироваться и удалять записи с ttl, даже если в капле по факту оказалось проэкспайренных ключей не 10Гб, а 9Гб, нет?

2016-12-10 09:15 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        self.preaggregate_query = """
7459417 Host: n0286-sas.hahn.yt.yandex.net:9012
7459418 Error: {"attributes"={"fid"=18446486516982214696u;"tid"=7467061416912571830u;"datetime"="2016-12-10T09:00:01.002785Z";"pid"=689961;"host"="n0286-sas-i.hahn.yt.yandex.net"};"        code"=1;"inner_errors"=[{"attributes"={"fid"=18446486516806784911u;"tid"=17803177109177937207u;"datetime"="2016-12-10T08:59:58.696003Z";"pid"=689961;"exit_code"=134;"host"="        n0286-sas-i.hahn.yt.yandex.net"};"code"=10000;"message"="Process exited with code 134"}];"message"="User job failed"}
7459419 Stderr:
7459420 Loaded UDF module: Python, from ./ff61ecc4-d093471c-d5022908-16, ABI version 1.3.0
7459421 Terminate was called, reason: Failed to compile module:   File "embedded:tounixdate", line 2
7459422     import time
7459423    ^
7459424 IndentationError: unexpected indent
7459425 
7459426 /bin/bash: line 1: 690024 Aborted                 ./cppbinary --yt-map "NYql::NAgent::TYQLYtMap<NYT::TNode>" 1 1
7459427 
7459428 Host: n4075-sas.hahn.yt.yandex.net:9012
7459429 Error: {"attributes"={"fid"=18446486516980997641u;"tid"=17742262749045998366u;"datetime"="2016-12-10T09:00:00.733057Z";"pid"=95760;"host"="n4075-sas-i.hahn.yt.yandex.net"};"        code"=1;"inner_errors"=[{"attributes"={"fid"=18446486516803133746u;"tid"=2209842740423266240u;"datetime"="2016-12-10T08:59:58.354727Z";"pid"=95760;"exit_code"=134;"host"="n4        075-sas-i.hahn.yt.yandex.net"};"code"=10000;"message"="Process exited with code 134"}];"message"="User job failed"}
7459430 Stderr:
7459431 Loaded UDF module: Python, from ./ff61ecc4-d093471c-d5022908-16, ABI version 1.3.0
7459432 Terminate was called, reason: Failed to compile module:   File "embedded:tounixdate", line 2
7459433     import time
7459434    ^
7459435 IndentationError: unexpected indent
7459436 
7459437 /bin/bash: line 1: 95867 Aborted                 ./cppbinary --yt-map "NYql::NAgent::TYQLYtMap<NYT::TNode>" 1 1
7459438 
7459439 Host: n0286-sas.hahn.yt.yandex.net:9012
7459440 Error: {"attributes"={"fid"=18446486516981519236u;"tid"=13285400733211156866u;"datetime"="2016-12-10T09:00:00.852335Z";"pid"=689966;"host"="n0286-sas-i.hahn.yt.yandex.net"};        "code"=1;"inner_errors"=[{"attributes"={"fid"=18446486516798787121u;"tid"=1799316744586959062u;"datetime"="2016-12-10T08:59:58.700245Z";"pid"=689966;"exit_code"=134;"host"="        n0286-sas-i.hahn.yt.yandex.net"};"code"=10000;"message"="Process exited with code 134"}];"message"="User job failed"}
7459441 Stderr:
7459442 Loaded UDF module: Python, from ./ff61ecc4-d093471c-d5022908-16, ABI version 1.3.0
7459443 Terminate was called, reason: Failed to compile module:   File "embedded:tounixdate", line 2
7459444     import time
7459445    ^
7459446 IndentationError: unexpected indent

2016-12-10 09:17 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        self.preaggregate_query = """
Специально воспроизвела повторно, чтобы получить лог. Краткий ответ - да, я меняла форматирование, но почему-то с импортными процедурами оно не работает. А поскольку не критично, то кажется не имеет смысл дергать YQL команду.

2016-12-12 14:49 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        for table in r.results:  # access to results blocks until they are ready
Так организован возвращаемый результат. Можно вместо итерации сказать "next(x for x in r.results)" или через itertools отрезать первый элемент. Если считаешь, что запись так аккуратнее, то могу попробовать так сделать в рамках переработки YQL запроса. Не уверена что ничего не поломается и что таблица действительно только одна (может они разбитые операции не сливают обратно вместе)

2016-12-12 14:50 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
В том, что он занял слишком много времени.

2016-12-12 14:58 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        :param date: data from which day to use for update
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 14:59 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    logger.exception("couple {!s} is invalid".format(row[0]))
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:00 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            # XXX: Prepare aggregate table from time to time, not always
Done in https://github.com/yandex/mastermind/pull/311/commits/63dda050e170bb80778d39c9eec3aabd8f24a186
Сделано немного по-другому,  но гарантии удовлетворяются (что один раз гарантируется добавленной проверкой таблицей, что нет параллельных операций вроде гарантирует лок)

2016-12-12 15:01 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                logger.error("empty result")
Расширила логгинг в https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df иначе действительно было неяно

2016-12-12 15:01 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        :param expired_threshold: a couples with expired volume above param are suspected
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:01 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        :return list of couples with expired date more then trigger
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:01 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    raise
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:01 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        raise AssertionError("YQL request attempts has exhausted {} {}".format(self._attempts, query))
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:01 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                        logger.error("YQL query result error {!s}".format(error))
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:02 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    logger.error("YQL failed #{}: {}[{}] ({},{!s})".format(attempt, result.status,
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:02 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                logger.exception("YQL ping excepted {}{}".format(self._cluster, self._token))
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:02 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                logger.exception("YQL ping excepted {}{}".format(self._cluster, self._token))
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:02 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                logger.exception("YQL ping excepted {}{}".format(self._cluster, self._token))
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:05 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        :param expired_threshold: a couples with expired volume above param are suspected
Fixed comment in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:05 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        Update aggregate table from YT. The processing may take up to ... time
Fixed comment in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:06 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        :return:
Fixed in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df and afterwards in 63dda05

2016-12-12 15:06 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            expired_threshold = self.params.get('ttl_cleanup', {}).get('ttl_threshold', 10737418240)
Fixed in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:06 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            # Configure parameters for work with IT
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:06 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        :return: list of couples with expired records volume above specified
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:06 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        logger.fatal("Create ttl_cleanup_job for couple {!s}".format(iter_group.couple))
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:06 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +    TTL_CLEANUP_LOCK = 'planner/couple_ttl_cleanup'
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:07 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +        self.aggregate_query = """
Done in https://github.com/yandex/mastermind/pull/311/commits/4732106cd00d7b48fb9a6db30b7cff4aef8db6df

2016-12-12 15:07 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            self.ttl_cleanup(request)
Done in https://github.com/yandex/mastermind/pull/311/commits/c9fc028033e45de4292205a01c9dc3a012109527

2016-12-12 15:07 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        couple_list = self._get_yt_stat()
Done

2016-12-12 17:34 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
Окей, ещё раз, объясни, пожалуйста, смысл:
- запрос выполняется 2 часа;
- мы дожидаемся ответа, через 2 часа получаем результат, пишем в лог, что вообще-то долго, нас не устраивает, и выкидываем результат.

Чем это лучше, чем:
- запрос выполняется 2 часа;
- мы дожидаемся ответа, через 2 часа получаем результат, пишем в лог, что вообще-то долго, нас не устраивает, но оставляем результат, раз уж мы его дождались.

2016-12-12 17:46 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
ну, когда это будет отдельный воркер, exception будет его прям взаправду except-ить. И организуем его попадание в желто-фиолетовые или как там цвет падения называется? И тогда все это не будет тихо проигнорировано. Но с другой стороны, Андрей Годин обещал мониторинг.

2016-12-12 17:56 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
Желто-фиолетовые - это про джобу. Здесь мы джобу ещё не создали, поэтому попадать в желто-фиолтевые некому.
Очень простой сайд-эффект, к которому приведет такое поведение -- мы будем ддосить yql без конца, раз уж они начали долго отвечать. Данные-то мы получить хотим. "Отвечали долго? Ничего, спросим ещё разок, уж постарайтесь в этот раз побыстрей".

2016-12-12 17:57 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            expired_threshold = self.params.get('ttl_cleanup', {}).get('ttl_threshold', 10737418240)
Оставь, пожалуйста, комментарий, что означает 10737418240.

2016-12-12 18:22 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                logger.error("empty result for table {} and trigger {}".format(aggregate_table, expired_threshold))
То, что это подозрительно, не означает, что это ошибка. Действительно возможна ситуация, когда на определенную дату не будет каплов с достаточным количеством проэкспайренных данных. Уровень `ERROR` тут неуместен.

2016-12-12 18:24 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +            count = 0
В случае исключения нельзя просто так продолжать работу, как будто мы убедились, что записей за текущую дату нет. А если в этом случае произошел кратковременный обрыв сети?

2016-12-12 18:29 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    logger.debug("couple {} is valid".format(couple))
Так и не понял, зачем это здесь? Я предлагаю вынести этот лог в место, где получаются результаты вызова `_get_yt_stat`, там будет доступен этот же список каплов, и можно будет написать что-то вроде `"пытаемся создать ttl cleanup джобу для капла X"`, это будет более информативно.

2016-12-13 07:16 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +            count = 0
try/except обработчик обрамляет только обработку результатов. except означает либо отсутствие данных либо данные не подходящего формата. Я специально ввела конструкции next (x for x in iterator) вместо (for x in iterator) потому что к последним нарекания. Но использование таких конструкций требует проверок или кидает исключение

2016-12-13 07:18 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    logger.debug("couple {} is valid".format(couple))
В дальнейшем будет фильтрация между списком валидных каплов и собственно списком джобов по историческим данным. Именно поэтому хочется увидеть список. Хочу заострить внимание, что уровень debug, а в проде включен уровень info (со слов Игоря)

2016-12-13 07:25 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                logger.error("empty result for table {} and trigger {}".format(aggregate_table, expired_threshold))
Перевела на warn

2016-12-13 10:04 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +            count = 0
Нет, `except` означает *любое* исключение, а не только "либо отсутствие данных либо данные не подходящего формата". Если ты обеспечишь перехватывание конкретных исключений, которые означают отсутствие данных, то никакого вопроса у меня не будет.
В этом случае нельзя игнорировать все исключения, я уже писал почему -- если внезапно сеть моргнула и мы не смогли выполнить `VALIDATE_QUERY`, то мы продолжим исполнение, а данные за эти сутки уже могут лежать в таблице.
BTW, `next(x for x in iterator)` - можно заменить на `next(iterator)`.

2016-12-13 12:19 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +            count = 0
> В этом случае нельзя игнорировать все исключения, я уже писал почему -- если внезапно сеть моргнула и мы не смогли выполнить VALIDATE_QUERY, то мы продолжим исполнение, а данные за эти сутки уже могут лежать в таблице.

send_query находится вне try/except блока. Или я не понимаю вопроса

> BTW, next(x for x in iterator) - можно заменить на next(iterator)

Не всегда.
```
In [1]: dd = {'a': 1, 'b': 2}

In [2]: next(dd)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-7c3c503bf1f5> in <module>()
----> 1 next(dd)

TypeError: dict object is not an iterator

In [3]: next(d for d in dd)
Out[3]: 'a'
```

2016-12-13 12:25 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +            count = 0
> send_query находится вне try/except блока. Или я не понимаю вопроса

Ок, согласен. Но это не мешает указать конкретный тип исключения, который происходит в случае отсутствия данных. Просто `except` использовать некорректно. В твоём случае это, скорее всего, StopIteration.

2016-12-13 12:27 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +            count = 0
Погоди, у тебя же Count(*), он не может не отдать результат (разве что случилось что-то серьезное, и значит, запрос не отработал и продолжать нельзя). Зачем тогда пропускать такой случай?

2016-12-13 12:36 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
Fixed

2016-12-13 12:37 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +            count = 0
Re-raise exception

2016-12-13 14:41 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        :param: couples with expired data size > expired_threshold are recommended to be cleaned
Этого параметра в функции нет

2016-12-13 14:47 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        if count >= 0:
Всё еще не понимаю, зачем это условие? `count` не бывает отрицательным.

2016-12-13 14:50 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +                    'wait_timeout': None, #get from config
Все эти параметры уже в примере конфига есть, почему мы их здесь не используем?

2016-12-13 15:01 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            job = self.job_processor._create_job(
Джоба может не создасться по разным причинам, например, при попытке создать джобу на капл, на котором джоба уже работает. В этом случае всё сломается.

2016-12-13 15:25 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +                    'wait_timeout': None, #get from config
Они из конфига извлекутся на уровне infrastructure

2016-12-14 14:06 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        :param: couples with expired data size > expired_threshold are recommended to be cleaned
Fixed

2016-12-14 14:06 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        if count >= 0:
Done

2016-12-14 14:06 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            job = self.job_processor._create_job(
Fixed

2016-12-14 15:36 UTC, nobodyisme commented
Пулл-реквест готов, будет замёржен вместе с пулл-реквестом в mastermind-qa.

2016-12-29 19:23 UTC, izhidkov commented on src/cocaine-app/yt_worker.py
> +                    result = request.results
здесь нужно понять, действительно ли request.results гарантирует завершение запроса и получение ответа, и если нет, обеспечить гарантию этого на нашей стороне.

2016-12-29 20:31 UTC, izhidkov commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
Нужно обернуть все взаимодействие с yql в нормальный таймаут. Одно дело, если зависнет standalone питонячий скрипт, совсем другое - если yql подвесит планнер.

2017-01-10 10:58 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    result = request.results
Ответ от yql-team.
----
При обращении к свойству results происходит просто polling статуса операции по operation_id с прогрессирующим периодом, который прекращается, если получился статус, отличный от означающих "в процессе". Вот нехитрый код это делающий: https://a.yandex-team.ru/arc/trunk/arcadia/kikimr/yql/library/python/yql/client/request.py?rev=2606973#L173-205
 
Понятно, что если специально задаться целью или наступить на условный баг - сделать бесконечно работающий запрос не сложно, так что гарантии никакой нет. Звучит как-будто автор цитаты просто хотел как-то туда передать timeout.
----
Напомню, что 1/ есть обещание от yql-team добавить timeout на ожидание, 2/ сейчас я работаю над тем, чтобы перевести ttl_cleanup_sched в отдельный воркер, то есть в худшем случае ошибка в YQL/YT повезет к повисанию ttl_cleanup_sched, но никак не целиком мастермайнда

2017-01-10 11:19 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                        if timeout and (end_time - start_time > timeout):
Обсудили с Игорем в offline (в Телеграмме). 1/ от yql-team есть обещание что они сделают таймаут, 2/ я уже приступила к работе над таской, которая выводит ttl_cleanup_planner в отдельный воркер.

2017-01-10 17:35 UTC, izhidkov commented on src/cocaine-app/yt_worker.py
> +                    result = request.results
В общем на самом деле ответ не совсем правдивый, либо отвечающий не понял вопроса либо что-то еще. В действительности оно не всегда дожидается результата, и иногда может возвращать объект со статусом RUNNING. Нам не обязательно знать конкретные причины, но тебе как мейнтейнеру кода в мастермайнд кажется стоило бы понять в нюансах как этот самый код работает, и что по крайней мере такое может быть. Для этого лучше все-таки самостоятельно взглянуть на сорцы yql клиента. Если это сделать, то можно прийти к выводу, что надо проконтролировать окончание yql запроса и получение результата на нашей стороне. Например это можно сделать вот так:
```
while request.results.status not in ['COMPLETED', 'ABORTED', 'ERROR']:
    time.sleep(delay)
result = request.results
```

2017-01-10 18:06 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    result = request.results
Добавь, пожалуйста, такую проверку, как предложил Игорь. Вне зависимости от возможных ошибок библиотеки (или их отстуствия) такое решение даст на нашей стороне гарантию того, что запрос действительно завершился.

2017-01-10 20:19 UTC, blinkov commented on src/cocaine-app/yt_worker.py
> +                    result = request.results
Если всё же соберетесь добавлять такой цикл, то список статусов лучше инвертировать (проверять на IDLE/PENDING/RUNNING): если внезапно появится новый финальный статус, то в исходном варианте случится бесконечный цикл, а так можно будет ещё раз проверить и громко упасть.

2017-01-10 20:47 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    result = request.results
Согласен. Ну тогда вот и эту финальную проверку вставить, что статус все-таки получился ожидаемым.
Спасибо.

2017-01-11 08:15 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    result = request.results
Меня волнует вопрос: от чего мы так тщательно предохраняемся? Иван, я правильно понимаю, что цикл излишен при нормальной работе библиотеке. А если в библиотеке будет баг, то такой цикл его сделает незаметным. Не лучше ли нам иметь повисший поток в случае бага в библиотеке, чтобы мы потом смогли отрепортить YQL-team ошибку с тем, чтобы ее починили. Благо повисший поток мы 1/ достаточно быстро продетектируем, 2/ он не приведет к фатальным последствиям в сервисе

2017-01-11 16:30 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    result = request.results
Вроде как разобрались от чего предохраняемся - не от повисания, а от некорректных результатов. 

Разбор с исходным кодом YQLя не дал ответа, от какого собственно случая спасает цикл Игоря. С его собственных слов это спасало от Running статуса на фоне is_success == False. И я вспомнила, что тоже с этим обращалась к Ивану Блинкову и он отвечал: 

> run() возвращает новый запрос, а не модифицирует то, что ты получила из query(), и ты его выкидываешь.
Тикет про то, чтобы сделать в этой ситуации нормальную диагностику: https://st.yandex-team.ru/YQL-1240
 
У меня проблема с running ушла после того, как я перешла c testing-а на автотесты, так что я забыла внести необходимую правку. Сейчас учла и обновила ревью. Скоро подойдет Игорь и посмотрит еще на код, может я неправильно его поняла.

2017-01-12 10:50 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    request = request.run()
Продолжаем.
Судя по коду библиотеки `request.run()` возвращает self, то есть сам же объект `request`. То есть, по факту никаких изменений в логике это нам не даёт. Давайте вернемся к идее проверки результатов, а не разбираться в тонкостях работы чужой библиотеки.

2017-01-12 14:40 UTC, annamel commented on src/cocaine-app/yt_worker.py
> +                    result = request.results
После обсуждений с Иваном, он согласился, что run() не возвращает новый запрос и ушел воспроизводить ту ошибку с RUNNING, которую наблюдали и я, и Игорь. А я залила изменения в виде https://github.com/yandex/mastermind/pull/311/commits/f24034784ade7af8df33365c3ecfee9d4d618f9e (просквошу после одобрения - Андрей предложил такой порядок вместо непосредственно сквоша)

2017-01-12 15:08 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +
Вчера мы договорились о том, что после того, как `while` завершился, мы должны проверить, какой статус получили, и в случае, если он неожиданный (например, не `COMPLETED`), мы делаем что-то с этим (пишем в лог и/или делаем повторный запрос).
Этого кода пока не вижу.

2017-01-12 16:09 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                    break
Здесь нужно написать в лог, какой статус в итоге оказался.
К тому же, если ты сделаешь тут `break`, будет кинуто исключение `YQL request attempts has exhausted`, что не правда. Нужно кидать исключение прямо отсюда. Тогда, наверное, уровнем выше логирование случится само по себе (?).

В случае статуса `UNKNOWN` мы должны продолжать ждать, потому что, судя по всему, этот статус мы видим тогда, когда на самом деле из YQL получить статус не удалось.

2017-01-14 18:08 UTC, nobodyisme commented on src/cocaine-app/yt_worker.py
> +                if not request.results.is_ok:
Тут нужно проверять не `request.results.is_ok`, а `request.is_ok`, именно эта проверка на статус изначального запроса.

2017-01-18 13:55 UTC, merged