Restore job: RO task
yandex/mastermind pull request #326
Opened 2016-12-07 15:47 UTC by Kanst

2016-12-07 16:18 UTC, nobodyisme requested changes

2016-12-07 16:18 UTC, nobodyisme commented on src/cocaine-app/jobs/restore_group.py
> +            self.BACKEND_stop_MARKER, base_path=src_backend.base_path).format(
Тут опечатка, `BACKEND_stop_MARKER`

2016-12-07 16:18 UTC, nobodyisme commented on src/cocaine-app/jobs/restore_group.py
> +            self.BACKEND_stop_MARKER, base_path=src_backend.base_path).format(
Разве этот маркер должен лежать в директории бекенда? Мне казалось, мы хотим создавать его на системном диске.

2016-12-07 16:18 UTC, nobodyisme commented on src/cocaine-app/jobs/restore_group.py
> +                    'create_stop_file': stop_src_backend})
Тут ещё не хватает пропускания `-114`

2016-12-07 16:21 UTC, nobodyisme commented
Можно ещё переименовать переменную `make_readonly` и не добавлять в её значение проверку статуса исходного бэкенда.
Что-нибудь вроде:
`restore_from_coupled_group = src_backend is not restore_backend`

И перенести её определение ближе к единственному месту использования.

2016-12-07 16:43 UTC, Kanst commented on src/cocaine-app/jobs/restore_group.py
> +            self.BACKEND_stop_MARKER, base_path=src_backend.base_path).format(
Так и есть. Просто mark_src_backend такой

2016-12-08 10:36 UTC, nobodyisme commented on src/cocaine-app/jobs/restore_group.py
> +    BACKEND_STOP_MARKER = config.get('restore', {}).get('backend_stop_marker')
Добавь, пожалуйста, пример `backend_stop_marker` в пример конфига `examples/mastermind.conf`.

2016-12-08 10:41 UTC, merged