Ttl sched history
yandex/mastermind pull request #366
Opened 2017-01-07 15:55 UTC by annamel

The further extending of ttl cleanup starter introduced in PR311. Now its efficiency could be managed by a few parameters, it considers history of job runs, it considers namespace attributes

2017-01-24 15:44 UTC, nobodyisme requested changes

2017-01-24 15:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        updated_values = {'recover_ts': int(recover_ts)} if recover_ts else {'cleanup_ts': int(cleanup_ts)}
Если `recover_ts is None`, это ещё не значит, что `cleanup_ts is not None`, поэтому так делать неправильно. И почему, например, нельзя обновить одновременно `recover_ts` и `cleanup_ts`?

2017-01-24 15:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        # prechecking for new or pending tasks
Почему `pending`? В статусах запроса ниже `PENDING` не вижу. Лучше использовать готовый список ACTIVE_STATUSES, который существует специально, чтобы не надо было набор статусов менять везде при добавлении новых.

2017-01-24 15:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +                logger.error("Not valid group is extracted from aggregation log {}{}".format(iter_group, type(iter_group)))
Зачем здесь нужно выводить тип объекта `iter_group`?

2017-01-24 15:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            iter_group = storage.groups[int(iter_group)]
На этом этапе `iter_group` не должен быть ничем иным, кроме `int`, поэтому приведение типа лишнее. От возможного несоответствия типов нужно избавляться раньше.

2017-01-24 15:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +                logger.error("Iter group is uncoupled {} {}".format(str(iter_group), iter_group))
Зачем тут группа печатается дважды? Это не нужно.

2017-01-24 15:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        Iterates all over couples. Find couples where ttl_cleanup hasn't run for more then 'period'
`period` - наверное, имелся ввиду `days_of_idle`?
`then` -> `than`

2017-01-24 15:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        for i in range(0, cursor.count(), READ_MONGO_CHUNK):
Зачем тебе такой сложный механизм работы с монгой? Если нужно вычитать все, просто итерируйся по результатам. Клиент монги сам вытягивает данные батчами. Если прямо хочется контролировать размер батча (в чем я сильно сомневаюсь), посмотри в сторону `cursor.batch_size`.

2017-01-24 15:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        logger.debug("Find couples where ttl_cleanup wasn't run since {} - {}".format(idleness_threshold, idle_groups))
Эта строчка лога будет печататься только если мы дошли до конца всего списка. Если мы делаем `return` выше по коду, то строчки в логе не будет. Когда `cleanup_ts` заполнится у всех каплов, она вообще перестанет появляться.

2017-01-24 15:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +                continue
Кажется, было бы очень хорошо учитывать уже запущенные джобы на ttl_cleanup, и не пытаться создать новые джобы на эти группы (например, `cleanup_ts` не меняется, пока джоба не завершится, а это значит, что при каждом обходе планировщика эта группа будет кандидатом, и будет пытаться создаваться новый джоб). 
Стоит добавить перехватывание ошибок взятия локов, потому что это будет самой частой ошибкой в этом месте, а уровень `exception` слишком избыточен в этом случае.

2017-01-24 17:43 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        # prechecking for new or pending tasks
Этот кусок вместе с комментарием я брала из recover_dc, который почитала за образец.

2017-01-24 18:19 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +                continue
Про перехватывание ошибок локов согласна (хотя опять же зря я возвела recover джоб на уровень эталон, он этого не делает). Про учет запущенных ttl_cleanup джобов - мне кажется не стоит. При умном планировщике такого момента вообще не будем. А сейчас мы теряем только незначительное число ресурсов на неудачную попытку старта

2017-01-24 18:28 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        updated_values = {'recover_ts': int(recover_ts)} if recover_ts else {'cleanup_ts': int(cleanup_ts)}
Сначала долго расписывала почему не стоит одновременно обновлять recover_ts и cleanup_ts и про синхронизацию стартеров. Но потом подумала, что действительно стоит обновлять оба значения: обнаружили новую каплу, так считаем что ее последний ttl_cleanup, он же последний recover равны дате, зафиксированной в бюро записей гражданских состояний (ака дата рождения). Кстати, проверка на "длину" массива не совсем корректна - может статься что одна капла умрет, а новая возникнет, а перечитки не случится. Но в принципе и в ttl и recover есть дополнительная валидация данных.

2017-01-24 18:48 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        for i in range(0, cursor.count(), READ_MONGO_CHUNK):
А почему ты вычитываешь кусками в recover?

2017-01-24 18:49 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        logger.debug("Find couples where ttl_cleanup wasn't run since {} - {}".format(idleness_threshold, idle_groups))
Поправила в https://github.com/yandex/mastermind/pull/366/commits/542154292bb28342a4d872e9cc66ce368a1e8682

2017-01-24 18:49 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        # prechecking for new or pending tasks
Поправила в https://github.com/yandex/mastermind/pull/366/commits/542154292bb28342a4d872e9cc66ce368a1e8682

2017-01-24 18:49 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +                logger.error("Not valid group is extracted from aggregation log {}{}".format(iter_group, type(iter_group)))
Поправила в https://github.com/yandex/mastermind/pull/366/commits/542154292bb28342a4d872e9cc66ce368a1e8682

2017-01-24 18:50 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            iter_group = storage.groups[int(iter_group)]
Поправила в https://github.com/yandex/mastermind/pull/366/commits/542154292bb28342a4d872e9cc66ce368a1e8682
Осталось от времени отладки кода

2017-01-24 18:50 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +                logger.error("Iter group is uncoupled {} {}".format(str(iter_group), iter_group))
Поправила в https://github.com/yandex/mastermind/pull/366/commits/542154292bb28342a4d872e9cc66ce368a1e8682

2017-01-24 18:50 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +                continue
Перехватывание ошибок лока добавила в https://github.com/yandex/mastermind/pull/366/commits/542154292bb28342a4d872e9cc66ce368a1e8682. Там уровень info

2017-01-24 19:02 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        for i in range(0, cursor.count(), READ_MONGO_CHUNK):
Потому что когда я писал этот код, про вычитывание батчами внутри самого клиента не знал.
Тогда вопрос следующий — зачем ты внедряешь новый механизм, который аналогичен моему, но реализован по-другому? Это в любом случае практика.

2017-01-24 19:15 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +        updated_values = {'recover_ts': int(recover_ts)} if recover_ts else {'cleanup_ts': int(cleanup_ts)}
Проблема заключается в том, что у тебя в функции есть несколько параметров, которые можно записать в базу. Сейчас по какой-то непонятной мне логике они сделаны взаимоисключающими, и вдобавок требуют, чтобы хотя бы один из них обязательно был передан. Хотя казалось бы, по названию функции, она должна по желанию своего клиента апдейтить все, что он передал.
Тем более, при использовании этой функции ты всегда вызываешь ее с одним аргументом, так что всё будет работать.
Я предлагаю на уровне этой функции решить общий случай — обновить "исторические" таймстемпы (раз уж она так называется).

2017-01-25 17:51 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        updated_values = {'recover_ts': int(recover_ts)} if recover_ts else {'cleanup_ts': int(cleanup_ts)}
Fixed in https://github.com/yandex/mastermind/pull/366/commits/4cc3dfb4378c8308c3b781c6d8a4c0b731d2a38d

2017-01-25 17:51 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +        for i in range(0, cursor.count(), READ_MONGO_CHUNK):
Fixed in https://github.com/yandex/mastermind/pull/366/commits/4cc3dfb4378c8308c3b781c6d8a4c0b731d2a38d

2017-01-26 10:38 UTC, nobodyisme requested changes

2017-01-26 10:38 UTC, nobodyisme commented on src/cocaine-app/balancer.py
> +                couple, err_msg = self._build_couple(
Такой подход применяется в Go, но несвойственен Python-у. Тут стоит применить исключения.

2017-01-26 10:38 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            logger.warn("No suitable uncoupled groups found {}".format(kwargs))
Печатать аргументы функции в таком виде не нужно, для меня это выглядит как мусор в логе. Если хочется понимать, с каким аргументами запускался поиск, это надо делать на том уровне, где семантика `kwargs` понятна, и нормально сформировать строчку лога, чтобы были понятны все параметры.

2017-01-26 10:38 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            logger.info("Suitable uncoupled groups for args {} are {}".format(kwargs, suitable_groups))
1) Аналогично предыдущему комментарию про `kwargs`.
2) `suitable_groups` печатать не стоит, потому что их порядок слишком большой, это могут быть тысячи групп.

2017-01-26 10:38 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            logger.info("No suitable uncoupled {}".format(str(self)))
Здесь не место для того, чтобы печатать своё состояние, это не какой-то особый случай.
Тем более, как минимум в одном месте пользователь `select()` сам безусловно логирует состояние селектора. Зачем это дублирование?

2017-01-26 10:38 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            logger.info("No groups in storage or args to select among them suitable uncoupled")
Эта строчка лога лишняя. То, что список групп был пустым, будет понятно из логирования состояния всего селектора.

2017-01-26 10:38 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            logger.info("Group is already coupled {}".format(str(group)))
Здесь логирование лишнее. Это приведет к появлению необоснованно большого числа записей в лог.

2017-01-26 10:42 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            if ns_settings and not ns_settings.attributes.ttl.enable:
Почему мы должны чистить капл, если `ns_settings is None`? Потенциально в этом коде это допускается.

2017-01-26 10:44 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +                logger.error("Iter group is uncoupled {}".format(str(iter_group)))
Не имеет смысла без повода явным образом приводить объект к строке, форматирование почти всегда всё правильно делает само.

2017-01-26 10:45 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +                logger.info("Failed to create a new job since couple/group are already locked by another job")
Здесь нужно в строку логирования добавить само исключения, чтобы было понятно, какие конкретно локи взять не удалось.

2017-01-26 10:47 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            couples_data = self.collection.find().sort('cleanup_ts', pymongo.ASCENDING)
Зачем ты второй раз вызываешь `find`? После `count()` он перестаёт возвращать результаты?

2017-01-26 10:49 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +            updated_values['cleanup_ts'] = int(cleanup_ts)
Если `updated_values` после проверки всех условий оказался пустой, запрос в монгу на `update` не имеет смысла делать. В этом случае можно успешно выйти из функции.

2017-01-26 10:50 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +            couples_data = self.collection.find().sort('cleanup_ts', pymongo.ASCENDING)
мы перестраиваем коллекцию и добавляем в нее новые данные. старый find не имел новых результатов.

2017-01-26 10:51 UTC, annamel commented on src/cocaine-app/planner/__init__.py
> +                logger.error("Iter group is uncoupled {}".format(str(iter_group)))
В этом случае не делает. Проверено. Будет писать "такой-то объект по такому-то адресу"

2017-02-06 12:21 UTC, nobodyisme commented on src/cocaine-app/balancer.py
> +                            couple, couple_groupset, self.node))
1) Переменная `couple_groupset` в данном контексте не определена (да, может присутствовать, но в общем случае не должна).
2) Зачем тут логировать объект эллиптиксовой ноды?

2017-02-06 12:21 UTC, nobodyisme commented on src/cocaine-app/balancer.py
> +                raise RuntimeError("Failed to find groups to couple {}/{}".format(groups_by_total_space, mandatory_groups))
1) Логировать `groups_by_total_space` в таком виде нельзя, это слишком большая структура данных.
2) Почему тут логируются именно `mandatory_groups`, а другие параметры нет? В чем состоит логика такого формата сообщения об ошибке?

2017-02-06 12:21 UTC, nobodyisme commented on src/cocaine-app/infrastructure.py
> +            logger.info("No suitable uncoupled")
Для чего эта строка здесь? Список выбранных `uncoupled`-групп логируется через метод ` __str__` селектора, там сразу видно, что список выбранных групп оказался пустым.

2017-02-06 12:21 UTC, nobodyisme commented on src/cocaine-app/planner/__init__.py
> +                logger.error("Iter group is uncoupled {}".format(str(iter_group)))
Такого быть не может, потому что правила форматирования объектов формализованы. Поскольку iter_group является инстансом Group, будет вызывать метод `Group.__str__`:

```
In [1]: class A(object):
   ...:     def __str__(self):
   ...:         return 'str'
   ...:     def __repr__(self):
   ...:         return 'repr'
   ...:

In [2]: a = A()

In [3]: 'Formatted a: {}'.format(a)
Out[3]: 'Formatted a: str'```

Проверь, пожалуйста, ещё раз. Если логироваться будет "такой-то объект по такому-то адресу", приведи, пожалуйста, конкретную строку, и разберемся, почему так происходит. Тогда можно будет эту проблему исправить глобально, потому что такого не должно происходить в принципе.

2017-02-06 13:34 UTC, annamel commented on src/cocaine-app/balancer.py
> +                            couple, couple_groupset, self.node))
1. Определена. На строке 974.  couple_groupsets = []. 
2. Про node удалила.

2017-02-06 13:38 UTC, annamel commented on src/cocaine-app/balancer.py
> +                raise RuntimeError("Failed to find groups to couple {}/{}".format(groups_by_total_space, mandatory_groups))
1. Ты прав, поправила. В тестах объект был маленький
2. ок, согласна

2017-02-06 13:41 UTC, annamel commented on src/cocaine-app/infrastructure.py
> +            logger.info("No suitable uncoupled")
ок

2017-02-06 13:57 UTC, nobodyisme commented on src/cocaine-app/balancer.py
> +                            couple, couple_groupset, self.node))
1.1) На строке 974 переменная определяется только при определенных условиях, а исключения ты перехватываешь вне зависимости от условий, которые приводят к исполнению строки 974.
1.2) В строке 1005 переменная `couple_groupset` переопределяется, поэтому вообще становится непонятно, что ты хочешь залогировать.

2017-02-08 13:17 UTC, merged