Mm sched: base
yandex/mastermind pull request #417
Opened 2017-02-20 17:16 UTC by annamel

This PR
- creates a copy of old planner in the new folder;
- starts a new API between starters and mm-sched (get_history, register_periodic_func, process_jobs): as the result the code of starters (ex parts of planner) decreased with this refactoring;
- introduces a new algorithm of resource crossing dependencies resolving. The algo works with old resource representation what would be changed in the next tasks.
The main code of mastermind is mostly untouched. 2 changes: initialization code of planner/scheduler and corresponding classes; condition in JobProcessor._ready_jobs

2017-02-26 20:09 UTC, nobodyisme requested changes

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +    def update_recover_ts(self, couple_id, ts):
Похожий метод `update_cleanup_ts`, который должен быть в методом объекта `planner`, отсутствует.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                logger.info('Another {} is already running under {} lock'.format(starter_func.__name__, lock_name))
Кажется, тут логичнее было бы использовать `starter_name` вместо `starter_func.__name__`.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                logger.exception('Failed to {}'.format(starter_name))
Странное сообщение об ошибке, `Failed to {starter_name}`, почему так?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            history[couple_str] = {'recover_ts': data_record.get('recover_ts')}
Почему здесь отсутствует `'ttl_cleanup_ts'`?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        add_couples = list(storage_couples - recover_data_couples)
Если ты используешь `storage.replicas_groupset` для сравнения с таблицей, надо использовать соответствующие названия переменных. Понятия `couple` и `replicas_groupset` не взаимозаменяемы.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
Sched_params and filter_func what?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                            (https://wiki.yandex-team.ru/users/aniam/mm-scheduler/#generacijadzhobovstartdzhobov)
Удали, пожалуйста, ссылку.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
Странное название "обработка джобов" для метода, который, судя по докстрингу, их не обрабатывает, а создает. `process_jobs` — обязанность `JobProcessor`, который назван соответствующим образом.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :param filter_func: Filter function are called before job creation to extra-check whether those jobs are needed
`Filter function are called` -> `Filter function is called`

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :return: a number of generated jobs
Почему возвращается количество созданных джобов? Было бы логичнее возвращать их список, а клиент мог бы делать с ними всё, что ему захочется, в том числе анализировать длину списка.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        job_report_resources = job_class.report_resources
Зачем эта отдельная переменная? Можно написать просто `job_class.report_resources(job_param)`.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        self.starters.append(starter)
Для чего нужен список `self.starters`? Не вижу, чтобы он как-то использовался.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        for r in res_demand:
Если тебе нужны ключи и значения, используй `.items()` или `.iteritems()`.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            res_demand[("Group", g)] = 100
1) `"Group"` нужно вынести в константу.
2) Почему `Group` начинается с прописной, когда название всех остальных ресурсов — со строчной?
https://github.com/yandex/mastermind/blob/release-2.28/src/cocaine-app/jobs/job.py#L52
3) Что означает "100"? Из контекста это не понятно.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        for res_type in resources:
`iteritems()`

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            for addr in resources[res_type]:
Почему переменная называется `addr`, когда, например, в случае `Job.RESOURCE_FS`, это не `host.addr`?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                    # Assume that FS is always 100% utilized
Почему мы можем сделать такое предположение?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                    consumption = 100 / min(self.res_limits[job_type][res_type], 1)
`min(self.res_limits[job_type][res_type], 1)` — то есть, 0 или 1? Или лимиты могут быть отрицательными?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :return: a dict where keys are tuples (res_type, group) or (res_type, node_addr) or (res_type, node_addr, fs_id)
Слишком большая вариативность значений. Нельзя ли как-то все значения унифицировать?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                and values are consumption level
Нигде не описано, что такое `consumption level` и какая у него область значений.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :param errors: list of strings
1) Судя по коду, `errors` никогда заполняться не будет.
2) Такой способ сообщения об "ошибках" выглядит очень странно. В чём его смысл? Если хочешь их логировать, то логируй прямо на месте.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            logger.warn("Errors during resource aggregation are {}".format(set(errors)))
https://github.com/yandex/mastermind/pull/417/files#r103105110

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :param resources: See convert_resource_representation
Параметра `resources` в сигнатуре метода нет.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            crossing_jobs = self.get_resource_crossing(res)
Почему переменная называется `crossing_jobs`, хотя `get_resource_crossing` возвращает совсем не джобы?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :param crossing_jobs:  see return of get_resource_crossing
`crossing_jobs` на самом деле не джобы, название переменной нужно изменить, чтобы соответствовать значению.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                logger.info('Cannot stop job {} of type is {}'.format(job.id, job.type))
Странная форма сообщения:
`Cannot stop job 123 of type is move_job`

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            if job.status in (jobs.Job.STATUS_NOT_APPROVED, jobs.Job.STATUS_NEW):
Почему джобы такого же или меньшего приоритета указанных статусов должны отменяться без учёта `STOP_ALLOWED_TYPES`?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        # XXX: Now we cancel all jobs while we may be satisfied with less amount. Fix that
Когда эта проблема будет решена, как будут выбираться джобы для отмены?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            self.job_processor.stop_jobs_list(filter(lambda x: x.id in cancellable_jobs, existing_jobs))
Почему сюда нельзя просто передать `cancellable_jobs`?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                continue
Судя по всему, низкоприоритетный джоб с параметром `force` сможет отменить высокоприоритетный. Кажется, такая логика нам сейчас не требуется, поэтому её надо явным образом запретить.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            usage_if_cancel = 0  # how much of resource would be still consumed when we'd cancel all cancellable jobs
Если тут `usage` означает то же, что в других местах `consumption`, нужно поменять название переменной.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                        force=force)
Тут передавать `force` не нужно. Параметр `force` служит только для отмены джобов, а все нужные джобы уже должны были бы быть на этом этапе отменены.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +import itertools
Этот импорт нужно перенести в первый блок импортов.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +import timed_queue
Этот импорт нужно перенести в третий блок импортов.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        self.params = config.get('scheduler', {})
Из параметров конфигурации шедулера используются только период для стартеров и флаг включения. Так и задумывалось?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        self.namespaces_settings = namespaces_settings
Настройки неймспейсов нигде не используются, для чего они здесь?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        self.node_info_updater = niu
`node_info_updater` не используется, для чего он здесь?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        self.candidates = []
`candidates` не используется, для чего он здесь?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            for job_type in jobs.JobTypes.AVAILABLE_TYPES:
`itertools.product()`

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        The function takes old resources (equivalent to job.resources), "resource_limits" for each job type from config
В конфиге эти ограничения называются не `resource_limits`, а `resources_limits`.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            cancellable_jobs.append(job.id)
Насколько я понимаю, к этому моменту `job` уже может выполниться, но его статус никак не проверяется, и потом произойдёт попытка его отмены. Такая ситуация возможна?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
`filter_func` на самом деле не используется совсем. Если он будет использоваться позже, добавлять его тоже нужно позже.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/__init__.py
> +    planner_new = config.get('scheduler', {}).get('enabled', False)
Так `planner` или `scheduler`?

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/__init__.py
> +        planner = Scheduler(meta_db, niu, job_processor, namespaces_settings)
Переменная `planner` активным образом используется выше, не нужно её тут переопределять.

2017-02-26 20:09 UTC, nobodyisme commented on src/cocaine-app/__init__.py
> +def init_planner(job_processor, niu, namespaces_settings):
Разнеси, пожалуйста, инициализацию вещей, который остаются в старом планнере и должны работать и дальше, и тех, которые должны инициализироваться в зависимости от настройки конфига. Поскольку шедулер будет в будущем вынесен в отдельный воркер, удаление из этого модуля инициализации шедулера должно делаться просто. Например, удалением реализации одной функции и её вызова.

2017-02-27 08:45 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +    def update_recover_ts(self, couple_id, ts):
Да, потому что патчи, мерджащие эти изменения из ttl_cleanup я отложила (ты же говорил пока не вводить лишнего. В PR415 они есть).

2017-02-27 08:46 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        add_couples = list(storage_couples - recover_data_couples)
Не совсем поняла. Поясни. Если что, эти названия переменных вводила не я, - это из твоего исходного кода. И это замечание относится к критичным?

2017-02-27 08:48 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            history[couple_str] = {'recover_ts': data_record.get('recover_ts')}
Потому что соот-щие патчи из ttl_cleanup сюда не вмерджены. Ты же сам был сторонником минимизации этого PR. Патч, мерджащий изменения, отдельно. Если же речь о том, чтобы по-другому переразбить патчи и патчсчеты, то наверное это окажется некритичным комментарием?

2017-02-27 08:49 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                        force=force)
Move planner принудительно ставил force. Это было ошибкой/подпоркой?

2017-02-27 08:51 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            crossing_jobs = self.get_resource_crossing(res)
она возвращает список tuples (consumption_level, job_id)

2017-02-27 08:51 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        job_report_resources = job_class.report_resources
Относится к критичным замечаниям?

2017-02-27 08:52 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :return: a number of generated jobs
Хорошее замечание. В следующей версии поправлю

2017-02-27 08:52 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                            (https://wiki.yandex-team.ru/users/aniam/mm-scheduler/#generacijadzhobovstartdzhobov)
ок

2017-02-27 08:55 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param filter_func: Filter function are called before job creation to extra-check whether those jobs are needed
Предполагался список filter function. Но эта функциональность еще не поддержана, когда будут очереди, тогда потребуется детальное продумывание.

2017-02-27 09:06 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
> Sched_params and filter_func what?

Не поняла вопроса. Но наверное комментарий относится к некритичным?

> Странное название "обработка джобов" для метода, который, судя по докстрингу, их не обрабатывает, а создает. process_jobs — обязанность JobProcessor, который назван соответствующим образом.

Хорошее замечание, учту в следующей версии. Оно же не критично?

> filter_func на самом деле не используется совсем. Если он будет использоваться позже, добавлять его тоже нужно позже.

Тоже правда. Поправлю протототип в следующей версии

2017-02-27 09:09 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            self.job_processor.stop_jobs_list(filter(lambda x: x.id in cancellable_jobs, existing_jobs))
Ф-ия job_processor-а принимает объекты job-ов, a cancellable jobs - это job.id. Можно было бы заново из монги извлекать job по job_id, но мне показалось, что это лишняя работа

2017-02-27 09:16 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        # XXX: Now we cancel all jobs while we may be satisfied with less amount. Fix that
Я думаю, это будет многоходовка. 1/ однозначно отменять джобы которые целиком блочат ресурс. 2/ анализируем набор ресурсов после отмены, ранджируем джобы по суммарному объему заблокированных ресурсов из необходимых нам (например, если джоба А хочет и CPU, HOST_IN на машине Х и HOST_OUT на машине Y, а джоба B хочет только CPU на машине Y то отменяем джобу А в первую очередь) и постепенно "отменяя" джобы на каждом шаге проверяем не встанет ли наша джоба. 
Но это один из вариантов. По форме похоже что задачка относится к классу линейного программирования, нужно будет посмотреть - возможно получится более качественное решение

2017-02-27 09:17 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            usage_if_cancel = 0  # how much of resource would be still consumed when we'd cancel all cancellable jobs
ок. Поменяю в следующей версии.

2017-02-27 09:19 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            cancellable_jobs.append(job.id)
Да, ты прав. Это мое упущение. Я правильно понимаю, что здесь нужно защититься под sync_manager.lock(self.JOBS_LOCK, timeout=self.JOB_MANUAL_TIMEOUT) ?

2017-02-27 09:20 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                logger.info('Cannot stop job {} of type is {}'.format(job.id, job.type))
Уберу "is"

2017-02-27 09:24 UTC, annamel commented on src/cocaine-app/__init__.py
> +def init_planner(job_processor, niu, namespaces_settings):
ок

2017-02-27 09:28 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                continue
Не стоит запрещать. Это как раз для истории про то, что некоторые неприоритетные джобы в случае необходимости могут снять высокприоритетные. Помнишь, мы обсуждали про то что сейчас как бы два разных уровня приоритета - по ресурсам и по группам. И вот флажок force решает ситуацию из-за которой возникла эта разноприоритетная неразбериха.

2017-02-27 09:28 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param crossing_jobs:  see return of get_resource_crossing
это список джобов с их уровнем потребления.

2017-02-27 09:28 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param resources: See convert_resource_representation
поправлю в следующей версии

2017-02-27 09:29 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        for r in res_demand:
да, так более аккуратно. хорошо

2017-02-27 09:29 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            if job.status in (jobs.Job.STATUS_NOT_APPROVED, jobs.Job.STATUS_NEW):
ты прав, это не корректная логика

2017-02-27 09:30 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                    # Assume that FS is always 100% utilized
Из разговора с Андреем Годиным. В следующей уже идущей версии с измененным описанием ресурсов эта логика пересмотрена.

2017-02-27 09:31 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                    consumption = 100 / min(self.res_limits[job_type][res_type], 1)
Спасибо!

2017-02-27 09:31 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            for addr in resources[res_type]:
для части addr, для части нет - а как бы ты считал это более правильным назвать?  res_dest?

2017-02-27 09:34 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :return: a dict where keys are tuples (res_type, group) or (res_type, node_addr) or (res_type, node_addr, fs_id)
Предложи? Я думала, навскидку лучше варианта, чем такой развернутый "идентификатор" ресурса, я не нашла. Чтобы из него еще было быстро извлекать данные и быстро его конструировать. Строка мне здесь показалась и более громоздкой с точки зрения нагрузку на память и более громоздкой с точки зрения последующих с ней операций

2017-02-27 09:37 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param errors: list of strings
там есть set - уменьшающий количество ошибок. Например когда хост отсутствует почему-то в storage, а джобы на нем исполняются, раньше вылезали десятки ошибок. А теперь "компрессируется" и только одна

2017-02-27 09:38 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        self.starters.append(starter)
для human_dump. Не успела его еще дописать

2017-02-27 09:38 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                logger.exception('Failed to {}'.format(starter_name))
Failed to ttl_cleanup, Failed to recover_dc, Failed to move - вроде норм

2017-02-27 09:39 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            for job_type in jobs.JobTypes.AVAILABLE_TYPES:
поясни, пожалуйста?

2017-02-27 09:39 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        self.params = config.get('scheduler', {})
пока да

2017-02-27 09:39 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +import timed_queue
поясни?

2017-02-27 09:40 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +import itertools
Расскажи что есть первый/второй/третий блок импорта

2017-02-27 10:07 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +import itertools
Первый блок, импорты модулей из стандартной библиотеки:
https://github.com/annamel/mastermind/blob/99b0abc5fb19b015fb2241c2c650845c7fe04ead/src/cocaine-app/sched/__init__.py#L1-L5

Второй блок, импорт сторонних библиотек:
https://github.com/annamel/mastermind/blob/99b0abc5fb19b015fb2241c2c650845c7fe04ead/src/cocaine-app/sched/__init__.py#L7

Третий блок, импорт внутренних модулей:
https://github.com/annamel/mastermind/blob/99b0abc5fb19b015fb2241c2c650845c7fe04ead/src/cocaine-app/sched/__init__.py#L9-L18

2017-02-27 10:08 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +import itertools
`collections` тоже нужно перенести в первый блок вместе с `itertools`.

2017-02-27 10:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            for job_type in jobs.JobTypes.AVAILABLE_TYPES:
Твои циклы `for` друг от друга не зависят, поэтому вложенность можно заменить `itertools.product()`. Можешь почитать документацию.

2017-02-27 10:10 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                logger.exception('Failed to {}'.format(starter_name))
`starter_name` — название стартера, то есть существительное, поэтому я бы написал `Failed to run starter '{}'`, но это не критично.

2017-02-27 10:11 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        self.starters.append(starter)
Тогда было бы лучше убрать этот код.

2017-02-27 10:15 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :param errors: list of strings
Знать про эту особенность внутри функции совсем не нужно, это лишняя задача для неё. Если тебе это логирование правда нужно, пусть его будет много — это не стандартная ситуация.

2017-02-27 10:17 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :return: a dict where keys are tuples (res_type, group) or (res_type, node_addr) or (res_type, node_addr, fs_id)
https://github.com/yandex/mastermind/blob/master/src/cocaine-app/jobs/__init__.py#L197

Здесь это называется `res_val`, то есть `resource value`.

2017-02-27 10:18 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            for addr in resources[res_type]:
https://github.com/yandex/mastermind/blob/master/src/cocaine-app/jobs/__init__.py#L197

Здесь это называется `res_val`, то есть `resource value`.

2017-02-27 10:20 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :param crossing_jobs:  see return of get_resource_crossing
Нет, это не список джобов. Джоб - это объект класса `Job`, не нужно путать терминологию.

2017-02-27 10:20 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                continue
> Это как раз для истории про то, что некоторые неприоритетные джобы в случае необходимости могут снять высокприоритетные.
Сейчас такая необходимость присутствует?

2017-02-27 10:23 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            cancellable_jobs.append(job.id)
Если ты в этом месте возьмёшь лок, это не будет означать, что статус не успел поменяться раньше. Нужно убедиться в том, что джоб можно отменять. Брать глобальный лок сейчас плохая практика, он держится очень долго.
На данном этапе достаточно будет проверить статус.

2017-02-27 10:26 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
> Не поняла вопроса. Но наверное комментарий относится к некритичным?

"Sched_params and filter_func" выглядит как незаконченное предложение. Я не понял, для чего эти слова в докстринге?

2017-02-27 10:26 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
> Хорошее замечание, учту в следующей версии. Оно же не критично?

А в чем сложность изменить это сейчас?

2017-02-27 10:33 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        add_couples = list(storage_couples - recover_data_couples)
Мой исходный код не учитывал `groupsets`, потому что на тот момент их не существовало. Сейчас существует, поэтому нужно адаптировать код соответствующим образом. 
Да, это критичное замечание, потому что приводит к путанице, когда читаешь код.

2017-02-27 10:40 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        job_report_resources = job_class.report_resources
Нет.

2017-02-27 10:41 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                            (https://wiki.yandex-team.ru/users/aniam/mm-scheduler/#generacijadzhobovstartdzhobov)
Это нужно убрать в рамках текущего пулл-реквеста.

2017-02-27 10:45 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            usage_if_cancel = 0  # how much of resource would be still consumed when we'd cancel all cancellable jobs
Это не критично. Если не можешь по какой-то причине изменить сейчас, не изменяй вообще.

2017-02-27 10:52 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                        force=force)
`Move planner` не занимался отменой мешающих джобов, а твой шедулер занимается. Поэтому этого здесь быть не должно.

2017-02-27 10:53 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            crossing_jobs = self.get_resource_crossing(res)
Джоб - это объект класса Job, не нужно путать терминологию. Это критичное замечание.

2017-02-27 10:54 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +import timed_queue
https://github.com/yandex/mastermind/pull/417#discussion_r103172070

2017-02-27 12:57 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        self.starters.append(starter)
Не совсем согласна. Мне было бы странно видеть что создаются какие-то сущности (читай расписание) и нигде в объекте не остается информации об этом. Это критично?

2017-02-27 12:59 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param errors: list of strings
Я с таким уже столкнулась, ты сказал что это не опасно, а лог загадился капитально. Если замечание не критичное, то я бы сохранила этот компрессированный вывод. Если замечание критично, то обоснуй что конкретно смущает.

2017-02-27 13:00 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :return: a dict where keys are tuples (res_type, group) or (res_type, node_addr) or (res_type, node_addr, fs_id)
Это ты про унифицировать разные типы tuples или замечание относилось к addr?

2017-02-27 13:29 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        for r in res_demand:
Здесь не ключи и значения. Мы получаем ключ, а потом - внимание - используем self.res, то есть значение по ключу берем от другого объекта

2017-02-27 13:30 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param crossing_jobs:  see return of get_resource_crossing
это список id джобов с их уровнем потребления

2017-02-27 13:32 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                continue
Поскольку я в явном виде убираю старую историю, то я обязана оставить хотя бы закладки на новую. Замечание критично?

2017-02-27 13:38 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            cancellable_jobs.append(job.id)
проверить статус опять из монги в смысле?

2017-02-27 13:41 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
> А в чем сложность изменить это сейчас?
Я не понимаю, зачем неиспользуемые переменные должны остаться и в чём сложность их убрать, но в рамках "критично — не критично" это не критично.

FilterFunc убрать несложно. А вот process_job переименовать - потом во всех верхних патчах прийдется руками менять.  Если ж менять потом можно будет за одно нажатие в PyCharm без лишних ошибок переименовать

2017-02-28 10:11 UTC, annamel commented on src/cocaine-app/__init__.py
> +        planner = Scheduler(meta_db, niu, job_processor, namespaces_settings)
Done in https://github.com/yandex/mastermind/pull/417/commits/879ce74554565fdfc93ed5cf8a914b829944d6d8

2017-02-28 10:11 UTC, annamel commented on src/cocaine-app/__init__.py
> +    planner_new = config.get('scheduler', {}).get('enabled', False)
https://github.com/yandex/mastermind/pull/417/commits/879ce74554565fdfc93ed5cf8a914b829944d6d8

2017-02-28 10:11 UTC, annamel commented on src/cocaine-app/__init__.py
> +def init_planner(job_processor, niu, namespaces_settings):
Done in https://github.com/yandex/mastermind/pull/417/commits/879ce74554565fdfc93ed5cf8a914b829944d6d8

2017-02-28 10:12 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                        force=force)
Done in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:12 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            crossing_jobs = self.get_resource_crossing(res)
Done in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:12 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                            (https://wiki.yandex-team.ru/users/aniam/mm-scheduler/#generacijadzhobovstartdzhobov)
Done in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:12 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param filter_func: Filter function are called before job creation to extra-check whether those jobs are needed
https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:13 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
2 of 3 comments are fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:13 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            usage_if_cancel = 0  # how much of resource would be still consumed when we'd cancel all cancellable jobs
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:13 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                logger.info('Cannot stop job {} of type is {}'.format(job.id, job.type))
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:13 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param crossing_jobs:  see return of get_resource_crossing
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:14 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param resources: See convert_resource_representation
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:14 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            for addr in resources[res_type]:
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:14 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        for res_type in resources:
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:14 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            res_demand[("Group", g)] = 100
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:14 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                and values are consumption level
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:14 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        The function takes old resources (equivalent to job.resources), "resource_limits" for each job type from config
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:15 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                logger.exception('Failed to {}'.format(starter_name))
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:15 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                logger.info('Another {} is already running under {} lock'.format(starter_func.__name__, lock_name))
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:15 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            for job_type in jobs.JobTypes.AVAILABLE_TYPES:
Fixed in https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e
Cпасибо за пояснение

2017-02-28 10:15 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        self.namespaces_settings = namespaces_settings
https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:15 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        self.node_info_updater = niu
https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:15 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        self.candidates = []
https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:15 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +import timed_queue
https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

2017-02-28 10:16 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +import itertools
https://github.com/yandex/mastermind/pull/417/commits/e7a0f53468278b6dc781abea9c82cb3cb7350f4e

Cпасибо за пояснение. Не знала о таком правиле.

2017-02-28 10:21 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        add_couples = list(storage_couples - recover_data_couples)
Андрей, я все еще не понимаю. Прогрепала проект - выборка из storage.replicas_groupset называется couples (balancer.py, planner/__init__.py). Как ты хочешь чтобы оно называлось? Не storage_couples, а replicas_groupset  например? И какая адаптация нужна?

2017-02-28 14:19 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        self.starters.append(starter)
Дело в том, что твоё расписание — это отдельная сущность, и словарь `starter` — тоже отдельная, и они не связаны явным образом.
Нет, это не критично, но если у тебя сейчас нет использования `starter`, оставь комментарий о том, как он будет использоваться в дальнейшем, — это критично.

2017-02-28 14:26 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :param errors: list of strings
Меня не устраивает следующее:
1) функция занимается заполнением какого-то стороннего списка помимо своей основной работы, — это плохая практика кода. Те проверки, которые она делает, чтобы заполнить этот массив, тоже не являются частью её основной работы, она это делает * только и именно* для заполнения этого массива.
2) создание массива из огромного (по твоим словам) количества строк — куча лишних аллоцирований и копирований в памяти (а ты, кажется, в этом же пулл-реквесте ратовала за оптимизацию);

Если хочешь ради дебага залогировать такие случаи, сделай это в специальном отдельном месте, где будет понятно, ради чего это всё происходит.

Это критичный комментарий.

2017-02-28 14:28 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :return: a dict where keys are tuples (res_type, group) or (res_type, node_addr) or (res_type, node_addr, fs_id)
Это я про то, что с точки зрения анализатора ресурсов должно быть два понятия — тип ресурса и значение ресурса. То, что конкретно собой представляет значение ресурса, в большинстве случаев ему должно быть всё равно. Специализированный по типу ресурса код лучше всего иметь в специальных отведенных для этого местах.

2017-02-28 14:29 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        for r in res_demand:
Разбираем:
```
for r in res_demand:
    self.res[r].append((res_demand[r], job_id))
```
`r` - ключ
`res_demand[r]` - внимание - значение

2017-02-28 14:36 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                continue
Да, замечание критично. Раз в этом функционале сейчас необходимости нет, его нужно убрать. Для того, чтобы проверить валидность кода, мне нужно продумать все варианты, а ты предлагаешь мне продумывать варианты для сценариев, необходимость в которых отсутствует. Это лишняя работа и повышение вероятности ошибиться.

2017-02-28 14:40 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            if job.status in (jobs.Job.STATUS_NOT_APPROVED, jobs.Job.STATUS_NEW):
Я и спрашиваю. Почему в случае, если джоб имеет меньший приоритет и находится, например, в статусе `NEW`, он отменится? При этом его тип на соответствие одному из `STOP_ALLOWED_TYPES` проверяться не будет.

2017-02-28 14:44 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        add_couples = list(storage_couples - recover_data_couples)
Каплы и групсеты — разные логические объекты. Поскольку ты работаешь с групсетами, соответствующие переменные должны иметь в названии упоминание `groupset` и не иметь `couple`. Записи в логе должны тоже этому соответствовать.
Второй вариант: работать с каплами, а не с групсетами. Для этого в переменных должно быть упоминание `couple`, а выборка должна производиться из объекта `storage.couples`.
С чем ты работаешь в этой функции  — с каплами или с групсетами?

2017-02-28 14:56 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            if job.status in (jobs.Job.STATUS_NOT_APPROVED, jobs.Job.STATUS_NEW):
Это соответствовало логике, реализованной в текущем планнере, и общему здравому смыслу: 1/ понятно что пытаемся снять только те джобы, которые меньшего приоритета, 2/ есть некоторые джобы еще не поставленные на исполнение - и их снимать "безболезненно", есть джобы поставленные на исполнение, но которые можно прервать в середине - их тоже можно снять. А есть те, которые оказавшись в стадии executing, прерывать нельзя. и вроде речь об этом

2017-02-28 14:56 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                continue
Fixed in https://github.com/yandex/mastermind/pull/417/commits/69574909fafa454bb1f62443cd1b2b78de089e76

2017-02-28 14:56 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        for r in res_demand:
Fixed in https://github.com/yandex/mastermind/pull/417/commits/69574909fafa454bb1f62443cd1b2b78de089e76

2017-02-28 14:57 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :return: a dict where keys are tuples (res_type, group) or (res_type, node_addr) or (res_type, node_addr, fs_id)
Это не относится к критичным?

2017-02-28 14:57 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        :param errors: list of strings
Fixed in https://github.com/yandex/mastermind/pull/417/commits/69574909fafa454bb1f62443cd1b2b78de089e76

2017-02-28 14:57 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        self.starters.append(starter)
Fixed in https://github.com/yandex/mastermind/pull/417/commits/69574909fafa454bb1f62443cd1b2b78de089e76

2017-02-28 15:03 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            if job.status in (jobs.Job.STATUS_NOT_APPROVED, jobs.Job.STATUS_NEW):
>  есть некоторые джобы еще не поставленные на исполнение - и их снимать "безболезненно"

Дай, пожалуйста, ссылку, где такое происходит в текущей реализации.

2017-02-28 15:04 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        :return: a dict where keys are tuples (res_type, group) or (res_type, node_addr) or (res_type, node_addr, fs_id)
Нет.

2017-02-28 15:09 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
Оставь TODO про переименование.

2017-02-28 15:11 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            cancellable_jobs.append(job.id)
Они только что были выбраны из монги в `existing_jobs`, у тебя есть объекты достаточной свежести.

2017-03-01 10:11 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            cancellable_jobs.append(job.id)
Я тебя не понимаю. :( Началось ведь с того, что "к этому моменту job уже может выполниться, но его статус никак не проверяется, и потом произойдёт попытка его отмены". если я проверила его статус в тот момент, когда формировала список отменяемых джобов, то повторная проверка статуса перед отменой непосредственно ничего не даст. Не так ли? Или ты про проверку на completed - чтобы их не пытаться отменять даже если они stoppable (а то self.res мы формировали уже давно, у джобы были неплохие шансы завершиться).

2017-03-01 10:30 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            cancellable_jobs.append(job.id)
Меня беспокоит следующий сценарий:
1) на этапе `update_resource_stat` происходит поиск активных джобов, и заполняется `self.res`
2) потом происходит потенциально долгое итерирование по `jobs_param_list` и вычисляются джобы, которые нужно отменить;
3) непосредственно в момент отмены какой-то выбранный для отмены джоб фактически уже может быть `COMPLETED`, попытка его отмены не завершится успешно.

2017-03-01 10:42 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            if job.status in (jobs.Job.STATUS_NOT_APPROVED, jobs.Job.STATUS_NEW):
https://github.com/yandex/mastermind/blob/release-2.28/src/cocaine-app/jobs/__init__.py#L577-L587

2017-03-01 10:55 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            if job.status in (jobs.Job.STATUS_NOT_APPROVED, jobs.Job.STATUS_NEW):
Отличия этого кода от твоего:
— этот код работает *только* при конфликте локов, то есть когда хочется сделать джоб на какую-то группу, на которую запущен другой джоб. Ты же распространяешь эту логику на любые ресурсы, это неправильно.
— этот код работает *только* при выставленном флаге *force*, который говорит "я точно хочу этот джоб, это важно!", а твой код отрабатывает всегда.

Совокупность этих двух условий позволяет мне отменить джоб на *конкретный капл/группу* и запустить на нём другой джоб.
Отменять джоб, работающий на потенциально другом капле/группе по конфликту ресурсов, да ещё и без флага `force`, как сделано у тебя, нельзя.

2017-03-01 11:38 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            if job.status in (jobs.Job.STATUS_NOT_APPROVED, jobs.Job.STATUS_NEW):
> — этот код работает только при конфликте локов, то есть когда хочется сделать джоб на какую-то группу, на которую запущен другой джоб. Ты же распространяешь эту логику на любые ресурсы, это неправильно.

Мы с тобой это обсуждали. У тебя была история про две разные категории приоритетов и два разных правила при работе с "хостовыми" ресурсами и с группой/каплом как ресурсом. Вроде мы разбирали разные случаи и пришли к выводу, что можно и без таких сложностей. Если возможно, разверни фразу "это неправильно". Какие конкретно контраргументы?

> — этот код работает только при выставленном флаге force, который говорит "я точно хочу этот джоб, это важно!", а твой код отрабатывает всегда.

Нет. У моего кода также проверка нам force. В самом начале, когда проверяются приоритеты. Менее приоритетная не может вытеснить без флага force. А более приоритетная конечно может и это логично. Иначе что это за приоритеты. 

Почему более приоритетная джоба не может отменить менее приоритетную? Зачем эта кооперативная многозадачность? Поясни, пожалуйста, логику.

2017-03-01 11:47 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            cancellable_jobs.append(job.id)
Обновила

2017-03-01 12:30 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +        Scheduler creates jobs with specified params of specified type. Sched_params and filter_func
done in https://github.com/yandex/mastermind/pull/417/commits/a28b68724525952483eefec5bfe390e2db11ef5b

2017-03-01 13:01 UTC, nobodyisme commented on src/cocaine-app/__init__.py
> +    if smart_scheduler:
А что, `smart_scheduler` может работать одновременно со старым `planner`? Зачем оставлена такая возможность?

2017-03-01 13:36 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        cancellable_jobs = []
Это не `jobs`, потому что здесь числа.

2017-03-01 13:37 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        completed_jobs = []
Это не `jobs`, потому что здесь числа.

2017-03-01 13:44 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                    res_demand[(Job.RESOURCE_FS, res_val[0], res_val[1])] = 100
Здесь нужно использовать не `Job.RESOURCE_FS`, а `res_type`, иначе при добавлении каких-нибудь новых типов ресурсов можно будет легко ошибиться.

2017-03-02 10:06 UTC, merged