Recovery starter
yandex/mastermind pull request #433
Opened 2017-03-03 10:57 UTC by annamel

Recovery starter relying on a new mm-sched-base

2017-03-05 20:34 UTC, nobodyisme requested changes

2017-03-05 20:34 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +        scheduler.register_periodic_func(self._do_recover_dc, 60*15, starter_name="recover_dc")
Тут нужно оставить комментарий про то, что такое константа `60*15` и обязательно передавать её значение через `keyword`-параметр по аналогии со `starter_name="recover_dc"`

2017-03-05 20:34 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +        for couple in storage.couples.keys():
Так есть же replicas_groupsets (https://github.com/yandex/mastermind/blob/release-2.28/src/cocaine-app/storage.py#L3024), почему не воспользоваться им?

2017-03-05 20:34 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +    def _get_top_weight_couples(self):
Эта функция возвращает не `top weight couples`, а вообще все каплы, которые нужно восстанавливать по определенному критерию. Название нужно поменять.

2017-03-05 20:34 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +        # sort weights (descending)
Очевидный комментарий не нужен, ровно это же самое написано кодом на следующей строке.

2017-03-05 20:34 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +        return sorted(weights, reverse=True)
Зачем функция возвращает список `tuple` из двух элементов?
Во-первых, в названии функции есть слова `get couples`, значит она должна возвращать каплы (а скорее даже replicas_groupsets, потому что `recovery` делается только на таких групсетах).
Во-вторых, веса снаружи функции никак не используются, поэтому возвращать их нет смысла.

2017-03-05 20:34 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +        self.params = config.get('scheduler', {}).get('recover_dc', {})
Опиши, пожалуйста, возможные настройки этого стартера в `examples/mastermind.conf`.

2017-03-05 20:34 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +
Между объектами на самом верхнем уровне модуля по стандартам оставляют одну или две строки, между классами и функциями — две.
https://pypi.python.org/pypi/autopep8 (E303)

Удали, пожалуйста, лишнюю строку.

2017-03-05 20:38 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +        self.job_processor = job_processor
Зачем тут `job_processor`?

2017-03-06 10:51 UTC, annamel commented on src/cocaine-app/sched/recover_starter.py
> +        return sorted(weights, reverse=True)
она возвращает tuples из двух элементов вместо одного, чтобы не создавать еще одну дополнительную промежуточную структуру (из списка tuples и так прийдется делать список словарей параметров

2017-03-06 10:53 UTC, annamel commented on src/cocaine-app/sched/recover_starter.py
> +        # sort weights (descending)
fixed in https://github.com/yandex/mastermind/pull/433/commits/934c87a29040c96b1422713157e19689a8ce9fcd

2017-03-06 10:53 UTC, annamel commented on src/cocaine-app/sched/recover_starter.py
> +        for couple in storage.couples.keys():
fixed in https://github.com/yandex/mastermind/pull/433/commits/934c87a29040c96b1422713157e19689a8ce9fcd

2017-03-06 10:53 UTC, annamel commented on src/cocaine-app/sched/recover_starter.py
> +    def _get_top_weight_couples(self):
fixed in https://github.com/yandex/mastermind/pull/433/commits/934c87a29040c96b1422713157e19689a8ce9fcd

2017-03-06 10:53 UTC, annamel commented on src/cocaine-app/sched/recover_starter.py
> +        scheduler.register_periodic_func(self._do_recover_dc, 60*15, starter_name="recover_dc")
fixed in https://github.com/yandex/mastermind/pull/433/commits/934c87a29040c96b1422713157e19689a8ce9fcd

2017-03-06 10:54 UTC, annamel commented on src/cocaine-app/sched/recover_starter.py
> +        self.params = config.get('scheduler', {}).get('recover_dc', {})
Это добавлю в общий патч по technical-debts (436). Так проще с точки зрения мерджа

2017-03-06 10:54 UTC, annamel commented on src/cocaine-app/sched/recover_starter.py
> +
Fixed in https://github.com/yandex/mastermind/pull/433/commits/934c87a29040c96b1422713157e19689a8ce9fcd

2017-03-07 14:09 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +        return sorted(weights, reverse=True)
Я не понимаю, на чём ты пытаешься сэкономить.
Если хотела сэкономить на памяти — тогда зачем ты используешь `sorted`, генерируя новый список?
Если хочешь не создавать новый список из групсетов на выходе, возвращай генератор, который тоже сэкономит тебе память.
К тому же, не решена проблема с тем, что функция называется `_get_groupsets*`, а возвращает не групсеты, а пары значений, это всё еще нужно поправить.

2017-03-09 10:02 UTC, annamel commented on src/cocaine-app/sched/recover_starter.py
> +        return sorted(weights, reverse=True)
Генератор здесь не нужен пока, так как params передается как список словарей и там уже отсекается. Про sorted - спасибо, это не учла

2017-03-09 10:24 UTC, KhasanovBI commented on src/cocaine-app/sched/recover_starter.py
> +        return groupset_weights.sort(reverse=True)
inplace методы ничего не возвращают по соглашению в питоне (так сделано, чтобы показать, что структура изменилась, а не создалась новая). sort использует [merge sort](https://github.com/python/cpython/blob/master/Objects/listobject.c#L1904) как я понял, так что память все равно будет аллоцироваться (это про замечание с sorted).

2017-03-09 14:30 UTC, nobodyisme commented on src/cocaine-app/sched/recover_starter.py
> +        for weight_groupset_pair in weight_groupsets:
JFYI, в питоне можно писать так:
```
for weight, groupset_id in weight_groupsets:
    ...
```
Если какие-то элементы тупла не интересны (как в твоём случае неиспользуемые веса), то принято так:
```
for _, groupset_id in weight_groupsets:
    ...
```

2017-03-09 14:31 UTC, nobodyisme commented
Можно сквошить фикс-коммиты.

2017-03-10 10:36 UTC, merged