Ttl cleanup starter
yandex/mastermind pull request #434
Opened 2017-03-03 10:58 UTC by annamel

TTL cleanup starter relying on a new mm-sched

2017-03-10 13:18 UTC, nobodyisme requested changes

2017-03-10 13:18 UTC, nobodyisme commented on src/cocaine-app/jobs/ttl_cleanup.py
> +        res['groups'] = [g.group_id for g in couple.groups]
Ключ `'groups'` надо вынести в константу. Если есть желание, ключ `'resources'` тоже.

2017-03-10 13:18 UTC, nobodyisme commented on src/cocaine-app/jobs/ttl_cleanup.py
> +            raise ValueError("Invalid params {}".format(iter_group))
Для того, кто увидит исключение `Invalid params 5` будет неочевидно, что это означает. Сделай, пожалуйста, более понятное сообщение об ошибке.

2017-03-10 13:18 UTC, nobodyisme commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +
Здесь должна быть ещё одна пустая строка, `autopep8`.

2017-03-10 13:18 UTC, nobodyisme commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +                                         period_default=60*15,  # 15 minutes
Почему здесь такой маленький дефолтный период? Мы знаем, что `ttl_cleanup` — тяжёлый стартер.

2017-03-10 13:18 UTC, nobodyisme commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +            expired_threshold = self.params.get('ttl_cleanup', {}).get('ttl_threshold', 10 * float(1024 ** 3))  # 10GB
После этой строки безопасно продолжать, если `aggregation_table  == ''`? Если `base_table == ''`? Если `yt_cluster == ''`?

2017-03-10 13:18 UTC, nobodyisme commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +            return couple_list
Почему тут в названии переменной `couple`, снаружи её результат присваивается переменной с `group` в названии, а сама функция называется `_get_*_stat`? Приведи, пожалуйста, всё в консистентное состояние.
На всякий случай напомню, что `groups` в общем случае обозначает набор объектов типа `Group`, а `group_ids` - набор целых чисел, которые являются `id` групп.

2017-03-10 13:18 UTC, nobodyisme commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +                    {
Поправь, пожалуйста, отступы.

2017-03-10 13:18 UTC, nobodyisme commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +import datetime
`time` и `datetime` нужно перенести в первый блок импортов.

2017-03-10 17:20 UTC, annamel commented on src/cocaine-app/jobs/ttl_cleanup.py
> +        res['groups'] = [g.group_id for g in couple.groups]
Следующим на публикацию коммит, меняющий resource model. Поэтому пока нецелесообразно.

2017-03-10 17:21 UTC, annamel commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +import datetime
забыла запушить эти изменения. Хорошо

2017-03-10 17:36 UTC, annamel commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +
не запушила. сейчас будут

2017-03-10 17:37 UTC, annamel commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +            expired_threshold = self.params.get('ttl_cleanup', {}).get('ttl_threshold', 10 * float(1024 ** 3))  # 10GB
безопасно. Ну по yt-е при таких настройках мы ничего не найдем, но по истории какое-то число групп вытащим

2017-03-10 17:58 UTC, annamel commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +import datetime
fixed https://github.com/yandex/mastermind/pull/434/commits/5fbbb5ad5a36a25226ac702b5962feac4660e282

2017-03-10 17:58 UTC, annamel commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +
fixes in https://github.com/yandex/mastermind/pull/434/commits/5fbbb5ad5a36a25226ac702b5962feac4660e282

2017-03-10 17:59 UTC, annamel commented on src/cocaine-app/jobs/ttl_cleanup.py
> +            raise ValueError("Invalid params {}".format(iter_group))
fixed in https://github.com/yandex/mastermind/pull/434/commits/968d0fbf32e9a25f5713cb1d2e5c4d336cf6a401

2017-03-10 17:59 UTC, annamel commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +                                         period_default=60*15,  # 15 minutes
fixed in https://github.com/yandex/mastermind/pull/434/commits/968d0fbf32e9a25f5713cb1d2e5c4d336cf6a401

2017-03-10 18:00 UTC, annamel commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +            return couple_list
fixed in https://github.com/yandex/mastermind/pull/434/commits/968d0fbf32e9a25f5713cb1d2e5c4d336cf6a401

2017-03-10 18:00 UTC, annamel commented on src/cocaine-app/sched/ttl_cleanup_starter.py
> +                    {
fixed in https://github.com/yandex/mastermind/pull/434/commits/968d0fbf32e9a25f5713cb1d2e5c4d336cf6a401

2017-03-12 20:14 UTC, nobodyisme commented
Можно сквошить изменения.

2017-03-13 20:43 UTC, merged