Defrag starter
yandex/mastermind pull request #435
Opened 2017-03-03 10:59 UTC by annamel

Starter of defragmentation jobs relying on mm-sched

2017-03-05 20:50 UTC, nobodyisme requested changes

2017-03-05 20:50 UTC, nobodyisme commented on src/cocaine-app/jobs/couple_defrag.py
> +                   if params['is_cache_couple'] else
Откуда берётся гарантия, что этот ключ есть в `params`?

2017-03-05 20:50 UTC, nobodyisme commented on src/cocaine-app/sched/defrag_starter.py
> +        self.params = config.get('scheduler', {})
Опиши, пожалуйста, возможные настройки этого стартера в examples/mastermind.conf.
Почему настройки этого стартера лежат в корневой секции `scheduler`?

2017-03-05 20:50 UTC, nobodyisme commented on src/cocaine-app/sched/defrag_starter.py
> +        scheduler.register_periodic_func(self._do_couple_defrag, 60*15, starter_name="couple_defrag")
Тут нужно оставить комментарий про то, что такое константа 60*15 и обязательно передавать её значение через keyword-параметр по аналогии со starter_name="couple_defrag"

2017-03-05 20:50 UTC, nobodyisme commented on src/cocaine-app/sched/defrag_starter.py
> +        self.job_processor = job_processor
Зачем тут `job_processor`? Он не используется.

2017-03-05 20:50 UTC, nobodyisme commented on src/cocaine-app/sched/defrag_starter.py
> +                     'is_cache_couple': False})
Тут нужно поправить форматирование. После переноса строки стоит двойной отступ, это обязательно нужно убрать. Было бы хорошо поправить форматирование так, как это сейчас принято в мм:
```
job_params.append({
    'couple': str(couple),
    'is_cache_couple': False,
})
```

2017-03-05 20:50 UTC, nobodyisme commented on src/cocaine-app/sched/defrag_starter.py
> +        for couple in storage.couples.keys():
Здесь имеет смысл говорить о `replicas_groupsets`, а не о каплах.

2017-03-05 20:50 UTC, nobodyisme commented on src/cocaine-app/sched/defrag_starter.py
> +        return True
Не нужна ли проверка на то, что `files_removed_size` превышает определенное пороговое значение, которое можно задавать через конфиг? Чтобы не запускать дефрагментацию, если потенциальный объем освобождаемых данных мал. Если не нужна, то почему? Лучше всего проконсультироваться с админами.

2017-03-06 11:09 UTC, annamel commented on src/cocaine-app/sched/defrag_starter.py
> +                     'is_cache_couple': False})
Fixed in https://github.com/yandex/mastermind/pull/435/commits/7187c951234618234c17fda0fabfb3cf151fd8e4

2017-03-06 11:09 UTC, annamel commented on src/cocaine-app/sched/defrag_starter.py
> +        for couple in storage.couples.keys():
Fixed in https://github.com/yandex/mastermind/pull/435/commits/7187c951234618234c17fda0fabfb3cf151fd8e4

2017-03-06 11:10 UTC, annamel commented on src/cocaine-app/sched/defrag_starter.py
> +        return True
Ручку оставить полезно, согласна. https://github.com/yandex/mastermind/pull/435/commits/7187c951234618234c17fda0fabfb3cf151fd8e4

2017-03-06 11:10 UTC, annamel commented on src/cocaine-app/sched/defrag_starter.py
> +        self.params = config.get('scheduler', {})
не, не в корневой. Он просто не использовал ничего. Поправила https://github.com/yandex/mastermind/pull/435/commits/7187c951234618234c17fda0fabfb3cf151fd8e4
А конфиг опишу в 436

2017-03-06 11:10 UTC, annamel commented on src/cocaine-app/sched/defrag_starter.py
> +        scheduler.register_periodic_func(self._do_couple_defrag, 60*15, starter_name="couple_defrag")
https://github.com/yandex/mastermind/pull/435/commits/7187c951234618234c17fda0fabfb3cf151fd8e4

2017-03-06 11:10 UTC, annamel commented on src/cocaine-app/sched/defrag_starter.py
> +        self.job_processor = job_processor
https://github.com/yandex/mastermind/pull/435/commits/7187c951234618234c17fda0fabfb3cf151fd8e4

2017-03-06 11:11 UTC, annamel commented on src/cocaine-app/jobs/couple_defrag.py
> +                   if params['is_cache_couple'] else
https://github.com/yandex/mastermind/pull/435/commits/7187c951234618234c17fda0fabfb3cf151fd8e4 - но вообще-то там конечно в явном виде указывается

2017-03-07 13:55 UTC, nobodyisme commented on src/cocaine-app/jobs/couple_defrag.py
> +        couple = couples[couple]
Учитывая, что по кода `couple` может быть пустой строкой, здесь потенциально будет случаться неочевидное исключение.  Лучше в таком случае требовать указывать в `params` ключ `'couple'`, и если его нет, ругаться явным `ValueError`, что требуется `couple`.

2017-03-07 13:58 UTC, nobodyisme commented on src/cocaine-app/sched/defrag_starter.py
> +            period_default=60*15,  # 15 minutes
Почему используется такая странная логика — в конфиге стартера указывается, с какой периодичностью его запускать, но сам стартер про это не знает, а знает только про дефолтное значение. Вместо этого про настройку периода стартера внезапно знает шедулер, и использует, перезаписывая дефолтное значение, которые передал сам стартер.
Казалось бы, более очевидным поведением было бы, если бы шедулер принимал чёткий период, который стартер бы задавал, исходя из своего собственного конфига и известного ему дефолтного значения.

2017-03-07 14:01 UTC, nobodyisme commented on src/cocaine-app/sched/defrag_starter.py
> +        min_meaningful_dirty_size = self.params.get('min_removed_size', 0)
Зачем название переменной отличается от названия настройки? Давай не будем вводить путаницы.

2017-03-09 10:14 UTC, annamel commented on src/cocaine-app/sched/defrag_starter.py
> +            period_default=60*15,  # 15 minutes
Можно и так. В следующей версии поправлю (во всех стартерах и в mm-sched)

2017-03-09 10:15 UTC, annamel commented on src/cocaine-app/sched/defrag_starter.py
> +        min_meaningful_dirty_size = self.params.get('min_removed_size', 0)
https://github.com/yandex/mastermind/pull/435/commits/2181cab99fb4f363abec7a5c43c77a12d6e60821

2017-03-09 10:15 UTC, annamel commented on src/cocaine-app/jobs/couple_defrag.py
> +        couple = couples[couple]
https://github.com/yandex/mastermind/pull/435/commits/2181cab99fb4f363abec7a5c43c77a12d6e60821

2017-03-09 14:26 UTC, nobodyisme commented
Можно сковшить изменения.

2017-03-10 10:27 UTC, merged