Mm sched mov
yandex/mastermind pull request #448
Opened 2017-03-10 17:15 UTC by annamel

Starter for mov job

Based on PR434, 436

2017-03-15 21:58 UTC, nobodyisme requested changes
Пока я успел найти три места, где код либо не может работать вообще, либо структуры используются неверным образом.
Вот эти три места:
https://github.com/yandex/mastermind/pull/448/files#r106234805
https://github.com/yandex/mastermind/pull/448/files#r106289583
https://github.com/yandex/mastermind/pull/448/files#r106292053

Мне такое положение говорит о том, что код не проверялся должным образом, потому что выполнять свою задачу он в принципе не может. Поэтому дальше я этот пулл-реквест смотреть отказываюсь, пока ты не исправишь указанные проблемы и не убедишься, что код всё-таки работает так, как задумывалось.

2017-03-15 21:58 UTC, nobodyisme commented on src/cocaine-app/jobs/move.py
> +            res['groups'].append(gid)
В этом месте `gid` на самом деле не `group id`, а объект типа `Group`. Это, кажется, так быть не должно.

2017-03-15 21:58 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                                         period_default=1800,  # one per half an hour
`register_periodic_func` уже не принимает `period_default`.

2017-03-15 21:58 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        - the host must belong to DC that have uncoupled_percentage < avg and > max
Больше максимального? Чего максимального? Как может быть "больше максимального"?

2017-03-15 21:58 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        - the group must be FULL
У групп не бывает статуса `FULL`.

2017-03-15 21:58 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        - it should have enough uncoupled space on fs
Понятие `uncoupled space` не имеет смысла, `uncoupled` может быть только группа.

2017-03-15 21:58 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        - dst DC uncoupled space < src DC uncoupled space
Понятие `uncoupled space` не имеет смысла, `uncoupled` может быть только группа.
Почему в датацентре назначения должно быть меньше свободного места, чем в датацентре источника?

2017-03-15 21:58 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        - coupled groups of src should not belong to dst datacenter
Для консистентности было бы здорово поменять `datacenter` на `DC`.

2017-03-15 21:58 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        host_in_notcandidates = self.scheduler.get_busy_nodes_and_groups(host_in_demand)
Несколькими строчками выше результат `get_busy_nodes_and_groups` обрабатывается совершенно по-другому. `host_out_notcandidates` и `host_in_notcandidates` имеют похожие названия, но совершенно разные значения, но используются ниже по коду тоже похожим образом.
Как в итоге задумывалось?

2017-03-16 07:42 UTC, annamel commented
> Пока я успел найти три места, где код либо не может работать вообще, либо структуры используются неверным образом.
Вот эти три места:
https://github.com/yandex/mastermind/pull/448/files#r106234805
https://github.com/yandex/mastermind/pull/448/files#r106289583
https://github.com/yandex/mastermind/pull/448/files#r106292053

Мне такое положение говорит о том, что код не проверялся должным образом, потому что выполнять свою задачу он в принципе не может. Поэтому дальше я этот пулл-реквест смотреть отказываюсь, пока ты не исправишь указанные проблемы и не убедишься, что код всё-таки работает так, как задумывалось.

register_periodic_func - да, я не проверяла после rebase-а. Но, как ты понимаешь, rebase не влияет на логику исполнения, хотя может поломать интерпретацию. Безусловно, стоило проверить, но интуиция подсказывает что будет еще десяток комментариев, а я точно уверена что после них проверять нужно будет. Ну и конечно я могу указать на коммиты, не-мои коммиты, которые ломали интерпретацию кода в билдах уже. 

про group vs gid - я проверяла код. Другое дело, что я могла смотреть только более-менее эмпрически - чтобы код не падал, чтобы mov job-а запускалась в некоторых ДЦ, что какие-то группы фильтровались и пр. Что каждая из веток кода отработала. А как ты проверял move_planner, у тебя был точный тест?

Почему про get_busy_groups ты считаешь неправильным использование, причем неправильным на уровне логики работы я вообще не поняла. hostin и hostout работают относительно разных входных параметров, поэтому и выдают разные выходные значения. но поскольку одно из значений они выдают одинаковое, то оно просто игнорируется (не сохраняется). Наверное, не самое pythonic-way, но точно не повод говорить "я не буду смотреть дальше".

2017-03-16 07:50 UTC, annamel commented on src/cocaine-app/sched/move_starter.py
> +        - dst DC uncoupled space < src DC uncoupled space
> Понятие uncoupled space не имеет смысла, uncoupled может быть только группа.

uncoupled space - это термин, повсеместно используется в move planner-е. Поскольку на систему отсутстует документация и полагаться можно только на код, я предполагала названия закрепленные в коде легитимными. Подскажи более правильный термин чем uncoupled space. Примеры использования uncoupled space в move planner:
https://github.com/annamel/mastermind/blob/97f740f89c55beedca52ae368cd786c904291a24/src/cocaine-app/planner/move_planner.py#L217
https://github.com/annamel/mastermind/blob/97f740f89c55beedca52ae368cd786c904291a24/src/cocaine-app/planner/move_planner.py#L432
https://github.com/annamel/mastermind/blob/97f740f89c55beedca52ae368cd786c904291a24/src/cocaine-app/planner/move_planner.py#L555
https://github.com/annamel/mastermind/blob/97f740f89c55beedca52ae368cd786c904291a24/src/cocaine-app/planner/move_planner.py#L562

> Почему в датацентре назначения должно быть меньше свободного места, чем в датацентре источника?

Почему свободного? Uncoupled. Наверное я не совсем корректно сформулировала в комментарии - история про процент, а не про абсолютное значение. Соот-т логике, описанной в 
https://github.com/annamel/mastermind/blob/97f740f89c55beedca52ae368cd786c904291a24/src/cocaine-app/planner/move_planner.py#L118

2017-03-16 07:51 UTC, annamel commented on src/cocaine-app/sched/move_starter.py
> +        - the group must be FULL
Ты имеешь в виду, что правильнее писать couple, а не групп?

2017-03-16 07:52 UTC, annamel commented on src/cocaine-app/sched/move_starter.py
> +        - the host must belong to DC that have uncoupled_percentage < avg and > max
Больше минимального. Спасибо за внимательность к комментариям

2017-03-16 07:55 UTC, annamel commented on src/cocaine-app/jobs/move.py
> +            res['groups'].append(gid)
Спасибо. Я посмотрю на это место внимательнее. Скорее всего из-за этой ошибки не фильтровались пересечения по группам.

2017-03-16 07:57 UTC, nobodyisme commented
> да, я не проверяла после rebase-а

Это твоя обязанность — проверить и показать в пулл-реквесте работающий код.

>  Ну и конечно я могу указать на коммиты, не-мои коммиты, которые ломали интерпретацию кода в билдах уже.

Не понимаю, про что ты, но ок, укажи, интересно. И это не отменяет того, что после ребейза твой код должен работать, причём корректным образом.

> про group vs gid - я проверяла код.

Не знаю, как ты проверяла код, но проверки по пересечению групп в таком виде не должны были правильно работать.

> Почему про get_busy_groups ты считаешь неправильным использование, причем неправильным на уровне логики работы я вообще не поняла

> то оно просто игнорируется (не сохраняется) 

```
In [1]: def f():
   ...:     return 1, 2
   ...:

In [2]: host_in_notcandidates, busy_groups = f()

In [3]: host_in_notcandidates
Out[3]: 1

In [4]: host_out_notcandidates = f()

In [5]: host_out_notcandidates
Out[5]: (1, 2)
```

Оно никоим образом, конечно же, не игнорируется. Поэтому я опять прихожу к выводу, что код не проверялся должным образом.

2017-03-16 11:59 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    i = bisect.bisect_left(dst_candidates, src_total_space)
Элементами `dst_candidates` являются кортежи из двух значений `(место, group_id)`.
`src_total_space` является просто целым числом, по сути тем, что в кортеже выше есть `место`.
Как работает `bisect.bisect_left`, можно прочитать тут: https://docs.python.org/2/library/bisect.html#bisect.bisect_left

Вкратце, при таком использовании bisect_left `i` может иметь любое значение, потому что при исполнении алгоритма сравниваются `int` и `tuple`, а надо было бы сравнивать равнозначные типы. Моя ручная проверка дала следующие результаты: любой `int` меньше, чем любой `tuple`, поэтому `i` всегда будет иметь значение `0`.

2017-03-21 18:40 UTC, annamel commented on src/cocaine-app/sched/move_starter.py
> +                    i = bisect.bisect_left(dst_candidates, src_total_space)
Спасибо. Исправлено

2017-03-21 18:41 UTC, annamel commented on src/cocaine-app/sched/move_starter.py
> +        - coupled groups of src should not belong to dst datacenter
done

2017-03-21 18:45 UTC, annamel commented on src/cocaine-app/sched/move_starter.py
> +        - it should have enough uncoupled space on fs
этот термин используется широко в move planner-е. я на него опиралась. более правильно space occupied by uncoupled groups? но не слишком ли длинно для названия переменной?

2017-03-21 18:45 UTC, annamel commented on src/cocaine-app/sched/move_starter.py
> +                                         period_default=1800,  # one per half an hour
обновила

2017-03-21 19:49 UTC, KhasanovBI commented on src/cocaine-app/jobs/move.py
> +        res = {}
Ради интереса, почему бы не ужать создание словаря до одной инструкции (до 467 строчки)? Каждый раз по обращению в dict идет поиск в хэш таблице, понятно, что это быстрая операция, но хорошо было бы не дергать питон лишний раз. Ну и вроде читабельнее должно стать.

2017-03-22 04:27 UTC, annamel commented on src/cocaine-app/jobs/move.py
> +        res = {}
Не уверена, что поняла тебя. Буду благодарна, если ты раскроешь мысль.

2017-03-22 08:01 UTC, KhasanovBI commented on src/cocaine-app/jobs/move.py
> +        res = {}
Да, я имел в виду это, а почему читабельность будет хуже?

2017-03-22 09:41 UTC, annamel commented on src/cocaine-app/jobs/move.py
> +        res = {}
Я боюсь в этом предмете (=читабельности) о чем-то судить. Пусть Андрей решает.

2017-03-24 17:50 UTC, nobodyisme requested changes

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/jobs/move.py
> +        res = {}
"Одна инструкция" и "читаемость" ни в коем случае друг другу не противоречат, ты же это в других местах спокойно делаешь: 
https://github.com/yandex/mastermind/pull/448/files#diff-fb2080b0837031d6c86119fef995e8cfR141

Булат имеет ввиду то, что словарь можно создавать одной инструкцией вместо того, чтобы значение каждого ключа задавать отдельно, как ты делаешь в строках 458-465.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/jobs/move.py
> +        assert(all(type(gid) == int for gid in res['groups']))
Проверку типа объекта правильно делать с помощью функции `isinstance(gid, int)`.

Почему этот `assert` присутствует только в MoveJob? Он настолько же актуален и для всех других.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            # for disks collect all consumption into one variable
В комментарии написано, что мы суммируем `consumption` для всех дисков.

1) Разве здесь не нужно разделять `consumption` по разным дискам? Насколько я понял, для одного хоста тут мы суммируем `consumption` вообще всех дисков на нём.
2) Почему речь только про диски? Тут же суммируется и сеть, и CPU.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                hosts[res_desc[1]][res_desc[0]] += consumer[0]
Что такое `res_desc[0]`, `res_desc[1]`, `consumer[0]` — непонятно совершенно. В таких случаях правильный вариант — раскрывать значение `tuple`-ов в переменные:
```
res_type, host_addr = res_desc
```

Но поскольку ты допустила то, что `res_desc` может иметь разную длину, к сожалению остаётся только менее красивый вариант:

 ```
res_type, host_addr = res_desc[0], res_desc[1]
```

То же самое нужно сделать для `consumer`.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                busy_groups.append(res_desc[2])
Аналогично https://github.com/yandex/mastermind/pull/448/files#r107894749

Нужно явным образом обозначить, что такое `res_desc[0]`, `res_desc[2]`

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +                    logger.warn("suspicious group without configured backends {}".format(storage.groups[gid]))
Это не "подозрительная группа", это штатная ситуация. Когда одна из групп в капле недоступна с момента запуска мастермайнда, у неё будет пустой список бэкендов. Этот лог нужно убрать.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        scheduler.register_periodic_func(self._do_move, period_val=move_period, starter_name="move")
Возвращаясь к разговору про непонятные лог-сообщения:
https://github.com/yandex/mastermind/blob/release-2.28/src/cocaine-app/sched/__init__.py#L85

Хотя изменение было якобы сделано:
https://github.com/yandex/mastermind/pull/417#discussion_r103172525
https://github.com/yandex/mastermind/pull/417#discussion_r103419461

Для меня всё еще остаётся непонятным сообщение от шедулера `"Failed to move"`, потому что я не понимаю, что ему и куда хотелось подвигать.
А вот `"Failed to run starter 'move'"` никаких вопросов не вызывает.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        - the host must belong to DC that have uncoupled_percentage < avg and < max
Добавь, пожалуйста, более раскрытое описание того, что ты подразумеваешь под `max`. По этой строке абсолютно непонятно, что имеется ввиду, потому что `< max` читается как "меньше максимального", что всегда истина и не несёт в себе никакого смысла.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        - the host must belong to DC that have uncoupled_percentage > min
https://github.com/yandex/mastermind/pull/448/files#r107900440

Аналогично нужно описать, что такое в данном контексте `min`

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        - dst DC uncoupled space < src DC uncoupled space
Почему `uncoupled space` в `dst DC` должен быть меньше, чем в `src DC`?
Мы перевозим занятую группу из `src DC` в `dst DC` как раз потому, что там свободного места больше, а в `src DC` мы хотим занятое освободить.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        host_in_notcandidates, busy_group_ids = self.scheduler.get_busy_nodes_and_groups(host_in_demand)
Здесь второй раз переприсваивается `busy_group_ids`, так делать не стоит. Я уже писал, как этого правильно избежать:
```
a1, b = some_func()
a2, _ = some_func()
```

А вообще, то, что тебе приходится прибегать к таком ухищрениям, свидетельствует о плохом API.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +    def get_busy_nodes_and_groups(self, demand):
Почему в названии метода `nodes`, а возвращает `hosts`? В мастермайнде объекты `Node` и `Host` несут разный смысл.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +        Return a list of addresses of hosts that satisfy demand
Ничего не сказано о том, что возвращаются ещё и группы.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                dc = nb.node.host.dc
Здесь может кидаться исключение, если не удалось узнать `dc` для группы. Нужно перехватывать `CacheUpstreamError`, в коде есть много аналогичных мест.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    dcs[dc]["uncoupled_space"] += nb.stat.total_space
Кажется, `uncoupled_space` стоит расчитывать только для `good_uncoupled_groups`. Если группа не попала в этот список, то либо мы не хотим её использовать как `uncoupled`, либо она занята и скоро не будет `uncoupled`, либо ещё по каким-то другим причинам.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +            unc_percent = float(dc["uncoupled_space"])/dc["total_space"]
`dc` в мастермайнде — это строка-идентификатор датацентра. В этой же функции выше ты именно таким образом этим пользуешься. Тут `dc` означает совершенно другое, нужно переименовать и `dcs`, и `dc`.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +            dc["unc_percentage"] = unc_percent
`percent`, `percentage` — можно было бы выбрать что-то одно. В следующей строке опять та же история.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                                               for gid in str(x.couple).split(':'))
У объекта `Couple` есть аттрибут `groups`, который является списком объектов `Group`, являющихся частью капла. Парсить строковое представление капла для того, чтобы получать список групп, очень плохо.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                                               and storage.groups[int(gid)] in dst_dc_val["full_groups"]
`"full_groups"` - список, время поиска в нём — `O(n)`. Если, скажем, в датацентрах количество `full_groups` одинаковое, ты получаешь квадратичное время на фильтрацию. Учитывая, что `n` в данном случае далеко не малое, такой подход плох.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                uncoupled_sensitivity = self.params.get('uncoupled_diff_sensitive_percent', 2)
Почему дефолтное значение 2, а в examples.conf в качестве примера указано 1? В examples.conf логично показывать те же самые дефолтные значения.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                if dst_dc_val["unc_percentage"] > (src_unc_percentage + uncoupled_sensitivity):
1) `unc_percentage` — float, область значений 0..1. `uncoupled_sensitivity` — судя по дефолтному значению int, область значений 1..100. Как ты их складываешь?
2) в `dst_dc` **должно быть** больше свободного места, чем в `src_dc`, иначе зачем бы нам туда перевозить заполненные группы?
3) в следующей строке в лог-сообщении написано, что `unc_percentage` у `dst_dc` меньше, чем у `src`. Так как должно быть?

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    if len(group.node_backends) == 0:
`get_good_uncoupled_groups` возвращает группы с нужным числом бэкендов. Эта проверка тут лишняя.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +            self.avail = avail
`avail` — что это означает? Нужно либо понятно назвать, либо написать докстринг, в котором будет полное описание. Лучше первый вариант.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    dcs[dc]["uncoupled_space_per_fs"][nb.fs.fsid] += nb.stat.total_space
У тебя нет гарантии, что `fsid` уникален в пределах датацентра. Гарантия про уникальность есть только на уровне хоста, где живёт эта файловая система. 
Поэтому так складывать `total_space` неверно.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +            return self.avail < avail
Эта реализация предполагает, что объект типа `DstCandidate` всегда будет сравниваться с целым числом, но никогда с другим объектом `DstCandidate`.
Потому что в случае сравнения с другим объектом `DstCandidate` результат не будет иметь смысла. Исключения при этом не случится.
В чем смысл так делать? `sorted` тут правильно работать не будет:
https://github.com/yandex/mastermind/pull/448/files#diff-e270864acf107b548e294781a435474eR231

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    i = bisect.bisect_left(dst_candidates, src_total_space)
1) Опять история про то, что массив состоит из объектов одного типа, а место для вставки ты ищешь с помощью объекта другого типа. Так делать плохо. Видимо, для этого ты и реализовала `__lt__` таким образом, как сейчас. Это плохой подход. Вариант решения — использовать `SentinelCandidate`, который эмулирует `DstCandidate`, но содержит фейковый group_id (например, 0), и искать место для вставки с помощью него.
2) `bisect` работает с отсортированными списками, но сортировка предполагается **в прямом порядке**. Твой массив `dst_candidates` отсортирован **в обратном порядке**, и это не может работать. У `bisect_left` в этом случае остаётся только два выхода: либо он вернёт 0, либо вернёт длину `dst_candidates`, это зависит от того, чем закончится самое первое сравнение. Нужно чинить.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    # no need to find another pair for specified src. and do not use dst for the another src
Почему нет необходимости? Может быть, `src_group` выгодней перевести в другой `dst_dc`, потому что там больше свободного места. Как это учитывается?

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    dst_dc_val['uncoupled_groups'].remove(dst_group)
Есть случаи, когда исходная группа переезжает в другой дц и при этом занимает не одну `uncoupled_group`, а несколько (`uncoupled_group` + `merged_groups`). Здесь почему-то учитывается только одна `uncoupled_group`.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    dst_dc_val["uncoupled_space"] -= dst_candidate.avail
Почему из `uncoupled_space` датацентра вычитается место, которое занимали все `uncoupled`-группы, живущие на диске, а не только те, которые заменит собой `src_group`?

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    dst_dc_val["uncoupled_space_per_fs"][dst_group.node_backends[0].fs.fsid] -= dst_candidate.avail
`dst_dc_val["uncoupled_space_per_fs"][dst_group.node_backends[0].fs.fsid]` тут всегда равен `dst_candidate.avail` (потому что `dst_candidate.avail` так определяется выше).
Сооветственно,  `dst_dc_val["uncoupled_space_per_fs"][dst_group.node_backends[0].fs.fsid]` после этой строки всегда будет 0. Так задумывалось?

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +                    dst_candidates.remove(dst_candidate)
Почему никак не меняется состояние других `uncoupled`-групп, которые могли жить на том же диске, куда начинается перевозка? Они всё так же остались среди `dst_candidates`, их `.avail` никак не изменился, и они без проблем смогут участвовать в выборах кандидата для последующих `src_group`.

2017-03-24 17:50 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +
Касательно всего алгоритма:
— куда пропала полезная фича по уменьшению возможных комбинаций `src-dst` пар? Она в разы ускоряла весь процесс поиска подходящих перевозок.
— стратегия выбора dst_dc сейчас "жадная" (выбирается первая лучшая по месту группа в текущем `dst_dc`). С точки зрения алгоритма гораздо лучше было бы выбирать тот `dst_dc`, в котором больше свободного места на текущий момент.
— никак не учитываются группы, которые объединяются с `dst_group` при перевозке:
https://github.com/yandex/mastermind/pull/448/files#diff-e270864acf107b548e294781a435474eR283
Эта логика была раньше и никуда пропадать не должна, особенно учитывая, что твой стартер при поиске `dst_group` подыскивает её по месту **на диске**, где живёт группа, а не **в самой** `dst_group`. По факту места в `dst_group` может быть меньше, чем в `src_group`, но за счёт других `uncoupled`-групп на том же диске твой стартер всё равно её выберет в качестве кандидата и попробует туда `src_group` перевезти.

2017-03-24 18:01 UTC, annamel commented on src/cocaine-app/jobs/move.py
> +        assert(all(type(gid) == int for gid in res['groups']))
1/ Потому что патсчет про MoveJob, 2/ там уже лежит следующий патсчет, меняющий модель описания ресурсов

2017-03-24 18:01 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +    def get_busy_nodes_and_groups(self, demand):
а расскажешь тогда что есть node и что есть host? чтобы я понимала.

2017-03-24 18:09 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +            # for disks collect all consumption into one variable
Для сети и CPU такое суммирование оправдано. Для дисков в целом суммирование не оправдано, но у нас сейчас джобы не ищут хосты где диск не занят на сколько-то процентов. А проверки по дискам происходят при попытке создания джобы.

2017-03-24 18:09 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +                    logger.warn("suspicious group without configured backends {}".format(storage.groups[gid]))
ок. спасибо

2017-03-24 18:10 UTC, annamel commented on src/cocaine-app/sched/move_starter.py
> +                    dcs[dc]["uncoupled_space_per_fs"][nb.fs.fsid] += nb.stat.total_space
ок

2017-03-24 18:14 UTC, annamel commented on src/cocaine-app/sched/move_starter.py
> +        host_in_notcandidates, busy_group_ids = self.scheduler.get_busy_nodes_and_groups(host_in_demand)
всегда есть компромисс между некоторыми характеристиками. например аккуратностью/избыточностью АПИ и скоростью. Если не собирать busy_groups внутри ф-ии, то прийдется делать дополнительный проход на поиск busy_groups.

2017-03-24 21:40 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +    def get_busy_nodes_and_groups(self, demand):
`Host` - это сервер (или виртуальная машина). Идентифицируется ip-адресом (`storage.py`, класс `Host`). 
`Node` - эллиптиксовая нода, по-другому процесс `dnet_ioserv`, запущенный на каком-то хосте. Идентифицируется ip-адресом (хостом), номером порта и типом протокола (IPv4/IPv6). (`storage.py`, класс `Node`).

2017-03-24 21:42 UTC, nobodyisme commented on src/cocaine-app/sched/__init__.py
> +            # for disks collect all consumption into one variable
Что значит "для дисков суммирование не оправдано"? Зачем тогда оно делается?

Я так и не понял, что означает этот комментарий в коде. Что из него следует?

2017-03-24 21:54 UTC, nobodyisme commented on src/cocaine-app/sched/move_starter.py
> +        host_in_notcandidates, busy_group_ids = self.scheduler.get_busy_nodes_and_groups(host_in_demand)
Странная аргументация про "дополнительный проход". У тебя в `self.res` ключами являются названия ресурсов. Для того, чтобы собрать информацию о занятых хостах, тебе нужно пройтись по всем типам ресурсов **кроме** `groups` (у тебя в комментариях в функции прямо так и написано, что `groups` не могут быть в `demands`). Для того, чтобы собрать информацию о занятых группах, достаточно пройтись только по `self.res['groups']`. Ты делаешь и первое, и второе дважды.
Если уж говорить про эффективность, достаточно было бы и первое, и второе делать один раз (`demand` по `host_in` и `host_out` у тебя не пересекаются, поэтому даже занятые хосты можно было бы рассчитать за один проход)
.
Но если с хостами пришлось бы дублировать код ради эффективности, то с группами даже это делать не нужно было бы. Так что вместо того, что ты называешь "делать дополнительный проход" я наоборот говорил о том, что от "одного прохода можно было бы избавиться" (второго по `self.res['groups']`).

2017-03-27 11:01 UTC, annamel commented on src/cocaine-app/sched/__init__.py
> +    def get_busy_nodes_and_groups(self, demand):
спасибо

2017-11-23 14:02 UTC, closed without merging